# ==============================================================================
# Political Sphere — Composite Action: PR Comment
# ------------------------------------------------------------------------------
# Purpose:
#   Post a structured comment to a pull request for workflow status visibility.
#
# Metadata:
#   - Created: 2025-12-20
#   - Last updated: 2025-12-20
#
# Scope & Responsibilities:
#   - Does: publish a PR comment with a provided message body.
#   - Does NOT: decide comment content or when to run.
#
# Design Principles:
#   - Deterministic and non-interactive execution
#   - Minimal permissions (issues: write only when required)
#   - Clear validation of required inputs
#
# Dependencies:
#   - GitHub CLI (gh) available on the runner
#   - ./.github/actions/ps-banner
#   - tools/scripts/actions/ps-teardown/ps-pr-comment/ps-pr-comment-resolve-root.sh
#   - tools/scripts/actions/ps-teardown/ps-pr-comment/ps-pr-comment-validate-inputs.sh
#   - tools/scripts/actions/ps-teardown/ps-pr-comment/ps-pr-comment-post.sh
#   - tools/scripts/ci/validate-pr-refs.sh
#   - tools/scripts/branding/validate-inputs.sh
#
# Dependents:
#   - ./.github/workflows/pr-gates.yml
#
# Execution Model:
#   - Trigger: N/A (invoked by workflow steps)
#   - Type: composite action (internal-only)
#   - Invoked by: PR workflows when failures occur
#
# Security & Policy Notes:
#   - Secrets: requires github_token input for API auth
#   - Permissions: issues: write required in caller
#   - Constraints: only posts to the current repo
#
# Operational Notes:
#   - Timeouts: controlled by the calling job
#   - Artifacts: none
#   - CI vs local: intended for CI only
# ==============================================================================

name: "PS PR Comment"
description: "Post a comment to a pull request"

inputs:
  pr_number:
    description: "Pull request number to comment on"
    required: true
  body:
    description: "Comment body (markdown supported)"
    required: true
  github_token:
    description: "GitHub token with issues: write"
    required: true
  expected_base_sha:
    description: "Optional expected base SHA for the PR"
    required: false
    default: ""
  expected_head_sha:
    description: "Optional expected head SHA for the PR"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Resolve scripts root
      shell: bash
      run: |
        resolve_root="${GITHUB_ACTION_PATH}/../../../tools/scripts/actions/ps-teardown"
        resolve_root="${resolve_root}/ps-pr-comment"
        resolve_script="${resolve_root}/ps-pr-comment-resolve-root.sh"
        bash "${resolve_script}"

    - name: Validate inputs
      shell: bash
      env:
        PS_PR_NUMBER: ${{ inputs.pr_number }}
        PS_BODY: ${{ inputs.body }}
        PS_TOKEN: ${{ inputs.github_token }}
        PS_EXPECTED_BASE: ${{ inputs.expected_base_sha }}
        PS_EXPECTED_HEAD: ${{ inputs.expected_head_sha }}
      run: |
        validate_root="${GITHUB_ACTION_PATH}/../../../tools/scripts/actions/ps-teardown"
        validate_root="${validate_root}/ps-pr-comment"
        validate_script="${validate_root}/ps-pr-comment-validate-inputs.sh"
        bash "${validate_script}"

    - name: Validate PR refs
      if: ${{ inputs.expected_base_sha != '' || inputs.expected_head_sha != '' }}
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        PS_PR_NUMBER: ${{ inputs.pr_number }}
        PS_EXPECTED_BASE_SHA: ${{ inputs.expected_base_sha }}
        PS_EXPECTED_HEAD_SHA: ${{ inputs.expected_head_sha }}
      run: |
        validate_root="${GITHUB_ACTION_PATH}/../../../tools/scripts/ci"
        validate_script="${validate_root}/validate-pr-refs.sh"
        bash "${validate_script}"

    - name: Post PR comment
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        PS_PR_NUMBER: ${{ inputs.pr_number }}
        PS_BODY: ${{ inputs.body }}
      run: |
        post_root="${GITHUB_ACTION_PATH}/../../../tools/scripts/actions/ps-teardown"
        post_root="${post_root}/ps-pr-comment"
        post_script="${post_root}/ps-pr-comment-post.sh"
        bash "${post_script}"
