# ==============================================================================
# Political Sphere — Composite Action: PS PR Comment
# License: Proprietary
# ==============================================================================
# ps_header_v: 6
#
# ─────────────────────────────────────────────────────────────────────────────
# IDENTITY
# ─────────────────────────────────────────────────────────────────────────────
# meta:
#   file_id: .github/actions/ps-teardown/ps-pr-comment/action.yml
#   file_type: action
#   language: yaml
#   version: 1.0.0
#   status: active
#   classification: internal
#   owner: political-sphere
#   last_editor: codex
#
# ─────────────────────────────────────────────────────────────────────────────
# LIFECYCLE & CHANGE CONTROL
# ─────────────────────────────────────────────────────────────────────────────
#   lifecycle:
#     created: 2025-12-28
#     last_updated: 2025-12-28
#     last_updated_mode: manual
#     review_cycle: 6 months
#     change_control: lightweight
#
# ─────────────────────────────────────────────────────────────────────────────
# CONTEXT
# ─────────────────────────────────────────────────────────────────────────────
# context:
#   parent_system: CI/CD Platform
#   initiative: Hardened CI
#
# ─────────────────────────────────────────────────────────────────────────────
# GOVERNANCE
# ─────────────────────────────────────────────────────────────────────────────
# governance:
#   intent: Provide the PS PR Comment composite action to Post a comment to a pull
#     request.
#   guarantees:
#     - Defines inputs and outputs for consistent downstream usage.
#     - Executes the composite steps declared in this action.
#     - Uses pinned external actions when referenced.
#   prohibitions:
#     - Does not grant permissions beyond the invoking workflow.
#     - Does not assume network access beyond runner policy.
#
# ─────────────────────────────────────────────────────────────────────────────
# INTERFACES
# ─────────────────────────────────────────────────────────────────────────────
# interfaces:
#   inputs: [pr_number, body, github_token, expected_base_sha, expected_head_sha]
#   outputs: [none]
#   exit_codes: [0=success, 1=failure]
#
# ─────────────────────────────────────────────────────────────────────────────
# EXECUTION
# ─────────────────────────────────────────────────────────────────────────────
# execution:
#   invocation: Used as a composite action step in GitHub Actions workflows.
#   example_invocation: >-
#     uses: ./.github/actions/ps-teardown/ps-pr-comment
#   model: deterministic
#   idempotency: not guaranteed
#
# ─────────────────────────────────────────────────────────────────────────────
# DEPENDENCIES
# ─────────────────────────────────────────────────────────────────────────────
# dependencies:
#   internal: [tools/scripts/actions/ps-teardown, tools/scripts/ci]
#   external: [bash]
#
# ─────────────────────────────────────────────────────────────────────────────
# SECURITY & POLICY
# ─────────────────────────────────────────────────────────────────────────────
# security:
#   permissions: [none]
#   secrets: [github_token]
#   network: restricted; depends on runner policy
#   policy_enforcement: [configs/ci/policies/allowed-actions.yml,
#     configs/ci/policies/action-pinning.yml,
#     configs/ci/policies/inline-bash.yml,
#     configs/ci/policies/section-headers.yml]
#
# ─────────────────────────────────────────────────────────────────────────────
# OPERATIONS
# ─────────────────────────────────────────────────────────────────────────────
# ops:
#   failure_modes: Step failures or validation errors surface as non-zero exits.
#   observability: Step logs are emitted in the GitHub Actions job output.
#   performance: Seconds to minutes depending on repo size and workload.
#
# ─────────────────────────────────────────────────────────────────────────────
# RISKS
# ─────────────────────────────────────────────────────────────────────────────
# risks:
#   assumptions:
#     - Inputs are provided as documented.
#     - Runner has required tooling for declared steps.
#   known_risks:
#     - Network or platform outages can interrupt execution.
#
# ─────────────────────────────────────────────────────────────────────────────
# RELATED
# ─────────────────────────────────────────────────────────────────────────────
# related:
#   references:
#     - tools/scripts/actions/ps-teardown
#     - tools/scripts/ci
#
# ==============================================================================

name: "PS PR Comment"
description: "Post a comment to a pull request"

inputs:
  pr_number:
    description: "Pull request number to comment on"
    required: true
  body:
    description: "Comment body (markdown supported)"
    required: true
  github_token:
    description: "GitHub token with issues: write"
    required: true
  expected_base_sha:
    description: "Optional expected base SHA for the PR"
    required: false
    default: ""
  expected_head_sha:
    description: "Optional expected head SHA for the PR"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Resolve scripts root
      shell: bash
      run: |
        resolve_root="${GITHUB_ACTION_PATH}/../../../tools/scripts/actions/ps-teardown"
        resolve_root="${resolve_root}/ps-pr-comment"
        resolve_script="${resolve_root}/resolve-root.sh"
        bash "${resolve_script}"

    - name: Validate inputs
      shell: bash
      env:
        PS_PR_NUMBER: ${{ inputs.pr_number }}
        PS_BODY: ${{ inputs.body }}
        PS_TOKEN: ${{ inputs.github_token }}
        PS_EXPECTED_BASE: ${{ inputs.expected_base_sha }}
        PS_EXPECTED_HEAD: ${{ inputs.expected_head_sha }}
      run: |
        validate_root="${GITHUB_ACTION_PATH}/../../../tools/scripts/actions/ps-teardown"
        validate_root="${validate_root}/ps-pr-comment"
        validate_script="${validate_root}/validate-inputs.sh"
        bash "${validate_script}"

    - name: Validate PR refs
      if: ${{ inputs.expected_base_sha != '' || inputs.expected_head_sha != '' }}
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        PS_PR_NUMBER: ${{ inputs.pr_number }}
        PS_EXPECTED_BASE_SHA: ${{ inputs.expected_base_sha }}
        PS_EXPECTED_HEAD_SHA: ${{ inputs.expected_head_sha }}
      run: |
        validate_root="${GITHUB_ACTION_PATH}/../../../tools/scripts/ci"
        validate_script="${validate_root}/validate-pr-refs.sh"
        bash "${validate_script}"

    - name: Post PR comment
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        PS_PR_NUMBER: ${{ inputs.pr_number }}
        PS_BODY: ${{ inputs.body }}
      run: |
        post_root="${GITHUB_ACTION_PATH}/../../../tools/scripts/actions/ps-teardown"
        post_root="${post_root}/ps-pr-comment"
        post_script="${post_root}/post.sh"
        bash "${post_script}"

    - name: Complete (PS)
      shell: bash
      run: |
        set -euo pipefail
        printf 'PS.TEARDOWN.PR_COMMENT: OK\n'
