# ==============================================================================
# Political Sphere — Composite Action: Preflight
# ------------------------------------------------------------------------------
# Purpose:
#   Centralize common preflight checks for composite actions (files/dirs/commands).
#
# Metadata:
#   - Created: 2025-12-20
#   - Last updated: 2025-12-20
#
# Scope & Responsibilities:
#   - Does: validate required files, directories, commands, and env vars.
#   - Does NOT: modify files or install dependencies.
#
# Design Principles:
#   - Deterministic and non-interactive
#   - Minimal, explicit inputs
#   - Reusable across actions to avoid duplication
#
# Dependencies:
#   - tools/scripts/branding/format.sh (if available)
#
# Dependents:
#   - ./.github/actions/lint
#   - ./.github/actions/typecheck
#   - ./.github/actions/test
#   - ./.github/actions/jscpd
#   - ./.github/actions/secret-scan-pr
#   - ./.github/actions/consumer-contract
#   - ./.github/actions/license-check
#
# Execution Model:
#   - Trigger: N/A (invoked by workflow steps)
#   - Type: composite action (internal-only)
#
# Security & Policy Notes:
#   - Secrets: none
#   - Permissions: inherited from the caller
#
# Operational Notes:
#   - Timeouts: controlled by the calling job
#   - Artifacts: none
# ==============================================================================

name: "PS Preflight"
description: "Common preflight checks (files, directories, commands, env vars)"

inputs:
  require_files:
    description: "Newline-separated list of files to require (repo-relative)"
    required: false
    default: ""
  require_dirs:
    description: "Newline-separated list of directories to require (repo-relative)"
    required: false
    default: ""
  require_commands:
    description: "Newline-separated list of commands required on PATH"
    required: false
    default: ""
  require_env:
    description: "Newline-separated list of required env vars"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Preflight checks
      shell: bash
      env:
        PS_REQUIRE_FILES: ${{ inputs.require_files }}
        PS_REQUIRE_DIRS: ${{ inputs.require_dirs }}
        PS_REQUIRE_COMMANDS: ${{ inputs.require_commands }}
        PS_REQUIRE_ENV: ${{ inputs.require_env }}

      run: |
        set -euo pipefail

        repo_root="${GITHUB_WORKSPACE:-$(pwd)}"
        format_sh="${repo_root}/tools/scripts/branding/format.sh"
        if [[ -f "${format_sh}" ]]; then
          # shellcheck source=tools/scripts/branding/format.sh
          . "${format_sh}"
        fi

        error() {
          if type -t ps_error >/dev/null 2>&1; then
            ps_error "$*"
          else
            echo "ERROR: $*" >&2
          fi
        }

        detail() {
          if type -t ps_detail >/dev/null 2>&1; then
            ps_detail "$*"
          else
            echo "$*"
          fi
        }

        check_lines() {
          local label="$1"
          local list="$2"
          local kind="$3"

          while IFS= read -r line; do
            local item
            item="$(echo "${line}" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
            if [[ -z "${item}" ]]; then
              continue
            fi

            case "${kind}" in
              file)
                if [[ ! -f "${repo_root}/${item}" ]]; then
                  error "${label} missing: ${item}"
                  exit 1
                fi
                ;;
              dir)
                if [[ ! -d "${repo_root}/${item}" ]]; then
                  error "${label} missing: ${item}"
                  exit 1
                fi
                ;;
              cmd)
                if ! command -v "${item}" >/dev/null 2>&1; then
                  error "${label} missing: ${item}"
                  exit 1
                fi
                ;;
              env)
                if [[ -z "${!item:-}" ]]; then
                  error "${label} missing: ${item}"
                  exit 1
                fi
                ;;
              *)
                ;;
            esac
          done <<< "${list}"
        }

        check_lines "Required file" "${PS_REQUIRE_FILES:-}" "file"
        check_lines "Required directory" "${PS_REQUIRE_DIRS:-}" "dir"
        check_lines "Required command" "${PS_REQUIRE_COMMANDS:-}" "cmd"
        check_lines "Required env var" "${PS_REQUIRE_ENV:-}" "env"

        detail "PS.PREFLIGHT: OK"
