# ==============================================================================
# Political Sphere — Composite Action: Evasion Scan
# License: Proprietary
# ==============================================================================
# ps_header_v: 6
#
# ─────────────────────────────────────────────────────────────────────────────
# IDENTITY
# ─────────────────────────────────────────────────────────────────────────────
# meta:
#   file_id: .github/actions/ps-task/security-evasion-scan/action.yml
#   file_type: action
#   language: yaml
#   version: 1.0.0
#   status: active
#   classification: internal
#   owner: political-sphere
#   last_editor: codex
#
# ─────────────────────────────────────────────────────────────────────────────
# LIFECYCLE & CHANGE CONTROL
# ─────────────────────────────────────────────────────────────────────────────
#   lifecycle:
#     created: 2026-01-02
#     last_updated: 2026-01-02
#     last_updated_mode: manual
#     review_cycle: 6 months
#     change_control: lightweight
#
# ─────────────────────────────────────────────────────────────────────────────
# CONTEXT
# ─────────────────────────────────────────────────────────────────────────────
# context:
#   parent_system: CI/CD Platform
#   initiative: Hardened CI
#
# ─────────────────────────────────────────────────────────────────────────────
# GOVERNANCE
# ─────────────────────────────────────────────────────────────────────────────
# governance:
#   intent: Detect lint evasion patterns and type safety erosion.
#   guarantees:
#     - Scans for @ts-ignore, eslint-disable, biome-ignore, shellcheck disable
#     - Detects TypeScript any type usage
#     - Produces structured JSON report
#     - Fails if thresholds exceeded
#   prohibitions:
#     - Does not grant permissions beyond the invoking workflow.
#     - Does not assume network access beyond runner policy.
#
# ─────────────────────────────────────────────────────────────────────────────
# INTERFACES
# ─────────────────────────────────────────────────────────────────────────────
# interfaces:
#   inputs: [ts_ignore_threshold, any_type_threshold]
#   outputs: [none]
#   exit_codes: [0=success, 1=threshold exceeded]
#
# ─────────────────────────────────────────────────────────────────────────────
# EXECUTION
# ─────────────────────────────────────────────────────────────────────────────
# execution:
#   invocation: Used as a composite action step in GitHub Actions workflows.
#   example_invocation: >-
#     uses: ./.github/actions/ps-task/security-evasion-scan
#   model: deterministic
#   idempotency: guaranteed
#
# ─────────────────────────────────────────────────────────────────────────────
# DEPENDENCIES
# ─────────────────────────────────────────────────────────────────────────────
# dependencies:
#   internal: [tools/scripts/runners/security/evasion-scan.js]
#   external: [none]
#
# ─────────────────────────────────────────────────────────────────────────────
# SECURITY & POLICY
# ─────────────────────────────────────────────────────────────────────────────
# security:
#   permissions: [none]
#   secrets: [none]
#   network: none required
#   policy_enforcement: [configs/ci/policies/allowed-actions.yml]
#
# ─────────────────────────────────────────────────────────────────────────────
# OPERATIONS
# ─────────────────────────────────────────────────────────────────────────────
# ops:
#   failure_modes: Non-zero exit if thresholds exceeded.
#   observability: JSON report at reports/evasion/evasion-scan.json
#   performance: Seconds; scans source files only.
#
# ─────────────────────────────────────────────────────────────────────────────
# RELATED
# ─────────────────────────────────────────────────────────────────────────────
# related:
#   references:
#     - tools/scripts/runners/security/evasion-scan.js
#     - docs/architectural-totems.md
#
# ==============================================================================

name: "Evasion Scan"
description: "Detect lint evasion patterns and type safety erosion"

inputs:
  ts_ignore_threshold:
    description: "Maximum allowed @ts-ignore directives (0 = strict)"
    required: false
    default: "0"
  any_type_threshold:
    description: "Maximum allowed TypeScript any types (0 = strict)"
    required: false
    default: "0"

runs:
  using: "composite"
  steps:
    - name: Run Evasion Scan (PS)
      uses: ./.github/actions/ps-task/ps-run
      with:
        id: "evasion-scan"
        title: "Evasion & complexity scan"
        description: "Detecting lint suppressions and type safety erosion"
        script: "node tools/scripts/runners/security/evasion-scan.js --ts-ignore-threshold=${{ inputs.ts_ignore_threshold }} --any-type-threshold=${{ inputs.any_type_threshold }}"
        require_files: |
          tools/scripts/runners/security/evasion-scan.js

    - name: Complete (PS)
      shell: bash
      run: |
        set -euo pipefail
        printf 'PS.TASK.EVASION_SCAN: OK\n'
