# ==============================================================================
# Political Sphere — Composite Action: Secrets Scan (PR)
# License: Proprietary
# ==============================================================================
# ps_header_v: 6
#
# ─────────────────────────────────────────────────────────────────────────────
# IDENTITY
# ─────────────────────────────────────────────────────────────────────────────
# meta:
#   file_id: .github/actions/ps-task/secret-scan-pr/action.yml
#   file_type: action
#   language: yaml
#   version: 1.0.0
#   status: active
#   classification: internal
#   owner: political-sphere
#   last_editor: codex
#
# ─────────────────────────────────────────────────────────────────────────────
# LIFECYCLE & CHANGE CONTROL
# ─────────────────────────────────────────────────────────────────────────────
#   lifecycle:
#     created: 2025-12-28
#     last_updated: 2025-12-28
#     last_updated_mode: manual
#     review_cycle: 6 months
#     change_control: lightweight
#
# ─────────────────────────────────────────────────────────────────────────────
# CONTEXT
# ─────────────────────────────────────────────────────────────────────────────
# context:
#   parent_system: CI/CD Platform
#   initiative: Hardened CI
#
# ─────────────────────────────────────────────────────────────────────────────
# GOVERNANCE
# ─────────────────────────────────────────────────────────────────────────────
# governance:
#   intent: Provide the Secrets Scan (PR) composite action to Run fast PR secret scan
#     via gitleaks.
#   guarantees:
#     - Defines inputs and outputs for consistent downstream usage.
#     - Executes the composite steps declared in this action.
#     - Uses pinned external actions when referenced.
#   prohibitions:
#     - Does not grant permissions beyond the invoking workflow.
#     - Does not assume network access beyond runner policy.
#
# ─────────────────────────────────────────────────────────────────────────────
# INTERFACES
# ─────────────────────────────────────────────────────────────────────────────
# interfaces:
#   inputs: [report_dir, log_dir]
#   outputs: [none]
#   exit_codes: [0=success, 1=failure]
#
# ─────────────────────────────────────────────────────────────────────────────
# EXECUTION
# ─────────────────────────────────────────────────────────────────────────────
# execution:
#   invocation: Used as a composite action step in GitHub Actions workflows.
#   example_invocation: >-
#     uses: ./.github/actions/ps-task/secret-scan-pr
#   model: deterministic
#   idempotency: not guaranteed
#
# ─────────────────────────────────────────────────────────────────────────────
# DEPENDENCIES
# ─────────────────────────────────────────────────────────────────────────────
# dependencies:
#   internal: [tools/scripts/security/secret-scan-pr.sh]
#   external: [none]
#
# ─────────────────────────────────────────────────────────────────────────────
# SECURITY & POLICY
# ─────────────────────────────────────────────────────────────────────────────
# security:
#   permissions: [none]
#   secrets: [none]
#   network: restricted; depends on runner policy
#   policy_enforcement: [configs/ci/policies/allowed-actions.yml,
#     configs/ci/policies/action-pinning.yml,
#     configs/ci/policies/inline-bash.yml,
#     configs/ci/policies/section-headers.yml]
#
# ─────────────────────────────────────────────────────────────────────────────
# OPERATIONS
# ─────────────────────────────────────────────────────────────────────────────
# ops:
#   failure_modes: Step failures or validation errors surface as non-zero exits.
#   observability: Step logs are emitted in the GitHub Actions job output.
#   performance: Seconds to minutes depending on repo size and workload.
#
# ─────────────────────────────────────────────────────────────────────────────
# RISKS
# ─────────────────────────────────────────────────────────────────────────────
# risks:
#   assumptions:
#     - Inputs are provided as documented.
#     - Runner has required tooling for declared steps.
#   known_risks:
#     - Network or platform outages can interrupt execution.
#
# ─────────────────────────────────────────────────────────────────────────────
# RELATED
# ─────────────────────────────────────────────────────────────────────────────
# related:
#   references:
#     - .github/actions/ps-task/secret-scan-pr/README.md
#     - tools/scripts/security/secret-scan-pr.sh
#
# ==============================================================================

name: "Secrets Scan (PR)"
description: "Run fast PR secret scan via gitleaks"

inputs:
  report_dir:
    description: "Report output directory (repo-relative)"
    required: false
    default: "reports/security"

  log_dir:
    description: "Log output directory (repo-relative)"
    required: false
    default: "logs/security"

runs:
  using: "composite"
  steps:
    - name: Secrets scan (PR) (PS)
      uses: ./.github/actions/ps-task/ps-run
      with:
        id: "secrets.pr"
        title: "Secrets scan (PR)"
        description: "Fast PR-scoped secret scan"
        script: "tools/scripts/security/secret-scan-pr.sh"
        require_files: |
          tools/scripts/security/secret-scan-pr.sh
        artifact_paths: |
          ${{ inputs.report_dir }}
          ${{ inputs.log_dir }}
        env_kv: |
          PS_REPORT_DIR=${{ inputs.report_dir }}
          PS_LOG_DIR=${{ inputs.log_dir }}

    - name: Complete (PS)
      shell: bash
      run: |
        set -euo pipefail
        printf 'PS.TASK.SECRET_SCAN_PR: OK\n'
