# ==============================================================================
# Political Sphere — Composite Action: PS Run
# ------------------------------------------------------------------------------
# Purpose:
#   Execute a repository script with standardized banner and section output.
#
# Metadata:
#   - Created: 2025-12-20
#   - Last updated: 2025-12-20
#
# Scope & Responsibilities:
#   - Does: print the PS banner, emit a section header, run a target script.
#   - Does NOT: install dependencies or manage permissions for the caller.
#
# Design Principles:
#   - Deterministic, non-interactive execution
#   - Path safety (no traversal outside allowed roots)
#   - CI-safe, structured output
#
# Dependencies:
#   - ./.github/actions/ps-banner
#   - tools/scripts/branding/print-section.sh
#   - Script provided via inputs.script (relative to platform repo root)
#
# Dependents:
#   - ./.github/actions/lint
#   - ./.github/actions/typecheck
#   - ./.github/actions/test
#   - ./.github/actions/jscpd
#   - ./.github/actions/build
#   - ./.github/actions/secret-scan-pr
#   - ./.github/workflows/release.yml
#
# Execution Model:
#   - Trigger: N/A (invoked by workflow steps)
#   - Type: composite action (internal-only)
#   - Invoked by: workflows and composite actions
#
# Security & Policy Notes:
#   - Secrets: inherited from the caller; not accessed directly
#   - Permissions: inherited from the caller
#   - Constraints:
#       - inputs.script must be a relative path (no traversal)
#       - inputs.working-directory must be a relative path (no traversal)
#
# Operational Notes:
#   - Timeouts: controlled by the calling job
#   - Artifacts: produced by the invoked script (if any)
# ==============================================================================

name: "PS Run"
description: "Run a platform script with a banner and section header"

inputs:
  id:
    description: "Section ID (machine-readable)"
    required: true

  title:
    description: "Section title"
    required: true

  description:
    description: "Optional section description"
    required: false
    default: ""

  script:
    description: "Script path to execute (relative to PLATFORM repo root)"
    required: true

  working-directory:
    description: "Working directory to run from (relative to WORKSPACE root)"
    required: false
    default: "."

  args:
    description: "Optional arguments to pass to the script (space-separated string)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Print banner
      uses: ./.github/actions/ps-banner

    - name: Run step (banner + section + script)
      shell: bash
      env:
        PS_REL_SCRIPT: ${{ inputs.script }}
        PS_REL_WD: ${{ inputs.working-directory }}
        PS_ARGS: ${{ inputs.args }}
        PS_ID: ${{ inputs.id }}
        PS_TITLE: ${{ inputs.title }}
        PS_DESCRIPTION: ${{ inputs.description }}
      run: |
        set -euo pipefail

        workspace_root="${GITHUB_WORKSPACE:-$(pwd)}"
        : "${PS_PLATFORM_ROOT:?PS_PLATFORM_ROOT must be set by the workflow (path to checked-out platform repo)}"
        platform_root="${PS_PLATFORM_ROOT}"

        if [[ ! -d "${platform_root}" ]]; then
          echo "ERROR: PS_PLATFORM_ROOT directory not found: ${platform_root}" >&2
          exit 1
        fi

        # Resolve print-section.sh (prefer platform, allow workspace fallback for dev/bootstrap).
        section_script=""
        for candidate in \
          "${platform_root}/tools/scripts/branding/print-section.sh" \
          "${workspace_root}/tools/scripts/branding/print-section.sh"; do
          if [[ -f "${candidate}" ]]; then
            section_script="${candidate}"
            break
          fi
        done

        if [[ -z "${section_script}" ]]; then
          echo "ERROR: print-section.sh not found." >&2
          echo "Tried: ${platform_root}/tools/scripts/branding/print-section.sh" >&2
          echo "Tried: ${workspace_root}/tools/scripts/branding/print-section.sh" >&2
          exit 1
        fi

        rel_script="${PS_REL_SCRIPT:-}"
        if [[ -z "${rel_script}" ]]; then
          echo "ERROR: inputs.script is required" >&2
          exit 1
        fi

        # Disallow absolute paths and traversal.
        if [[ "${rel_script}" = /* ]] || [[ "${rel_script}" == *".."* ]]; then
          echo "ERROR: inputs.script must be a relative path within the platform repo (no traversal)." >&2
          echo "Got: ${rel_script}" >&2
          exit 1
        fi

        target="${platform_root}/${rel_script}"
        if [[ ! -f "${target}" ]]; then
          echo "ERROR: script not found: ${target}" >&2
          exit 1
        fi

        rel_wd="${PS_REL_WD:-}"
        if [[ -z "${rel_wd}" ]]; then
          rel_wd="."
        fi

        if [[ "${rel_wd}" = /* ]] || [[ "${rel_wd}" == *".."* ]]; then
          echo "ERROR: inputs.working-directory must be a relative path within the workspace (no traversal)." >&2
          echo "Got: ${rel_wd}" >&2
          exit 1
        fi

        wd="${workspace_root}/${rel_wd}"
        if [[ ! -d "${wd}" ]]; then
          echo "ERROR: working directory does not exist: ${wd}" >&2
          exit 1
        fi

        printf 'PS.RUN: platform_root=%q\n' "$platform_root"
        printf 'PS.RUN: script=%q\n' "$rel_script"
        printf 'PS.RUN: working_directory=%q\n' "$rel_wd"

        bash "${section_script}" "${PS_ID}" "${PS_TITLE}" "${PS_DESCRIPTION}"

        cd "${wd}"

        args="${PS_ARGS:-}"
        if [[ -n "${args}" ]]; then
          # Intentional word-splitting: args is a workflow-author-controlled string.
          # Split into an array safely to preserve quoting semantics.
          read -r -a args_arr <<< "${args}"
          bash "${target}" -- "${args_arr[@]}"
        else
          bash "${target}"
        fi

        echo "PS.RUN: OK"
