# =================================================================================================
# Political Sphere — Composite Action: Tools Installer (ps-tools)
# -------------------------------------------------------------------------------------------------
# Purpose:
#   Consolidate tool installation into a single canonical action. Supports predefined bundles
#   (`lint` and `security`) plus arbitrary `extra_tools` and also accepts an explicit `tools`
#   newline-separated list when callers have already assembled the list.
#
# Design:
#   - `bundle`: "lint" | "security" | "none" (default: none)
#   - `extra_tools`: optional newline-separated list of additional tool ids
#   - `tools`: optional newline-separated explicit tool list (takes precedence if provided)
#   - Internally delegates to `ps-install-tools` which performs pinned, SHA-verified installs
# Example:
#   bundle: "lint"
#
# Notes:
#   - Keeps behaviour deterministic and reuses existing installer logic
#   - Backwards compatible with callers that provide an explicit list via `tools`
# =================================================================================================

name: "PS Tools"
description: "Install pinned CLI tools (bundle + extra_tools) using the pinned installer"

inputs:
  install_dir:
    description: "Installation directory for CLI tools (repo-relative)"
    required: false
    default: ".tooling/bin"

  bundle:
    description: "Predefined tools bundle to install (lint, security, none)"
    required: false
    default: "none"

  extra_tools:
    description: "Optional newline-separated list of extra tool ids to install (one per line)"
    required: false
    default: ""

  tools:
    description: "Optional explicit newline-separated tool list to install (one id per line). If provided, this takes precedence over bundle/extra_tools."
    required: false
    default: ""

  run_security_scans:
    description: "Run fast PR-oriented security scans after installing tools (1 = run, 0 = skip). Requires security bundle or tools providing gitleaks."
    required: false
    default: "0"

runs:
  using: "composite"
  steps:
    - name: Resolve platform/workspace roots
      shell: bash
      run: |
        set -euo pipefail

        platform_root="${PS_PLATFORM_ROOT:-}"
        workspace_root="${GITHUB_WORKSPACE:-}"

        if [[ -n "${platform_root}" && -d "${platform_root}" ]]; then
          scripts_root="${platform_root}"
          printf 'PS.TOOLS: scripts_root=PS_PLATFORM_ROOT (%s)\n' "${scripts_root}"
        elif [[ -n "${workspace_root}" && -d "${workspace_root}" ]]; then
          scripts_root="${workspace_root}"
          printf 'PS.TOOLS: scripts_root=GITHUB_WORKSPACE (%s)\n' "${scripts_root}"
        else
          printf 'ERROR: neither PS_PLATFORM_ROOT nor GITHUB_WORKSPACE is available\n' >&2
          exit 1
        fi

        printf 'PS_SCRIPTS_ROOT=%s\n' "${scripts_root}" >> "${GITHUB_ENV}"

    - name: Validate inputs
      shell: bash
      env:
        PS_BUNDLE_INPUT: ${{ inputs.bundle }}
        PS_EXTRA_INPUT: ${{ inputs.extra_tools }}
        PS_TOOLS_INPUT: ${{ inputs.tools }}
      run: |
        set -euo pipefail

        scripts_root="${PS_SCRIPTS_ROOT:?PS_SCRIPTS_ROOT not set}"

        validate_sh="${scripts_root}/tools/scripts/branding/validate-inputs.sh"
        if [[ ! -f "${validate_sh}" ]]; then
          printf 'ERROR: validate-inputs.sh not found at %s\n' "${validate_sh}" >&2
          exit 1
        fi

        # shellcheck source=/dev/null
        . "${validate_sh}"

        # If explicit `tools` is provided, we accept it as authoritative
        tools_raw="${PS_TOOLS_INPUT:-}"
        if [[ -n "${tools_raw}" ]]; then
          require_nonempty "inputs.tools" "${tools_raw}" || exit 1
          # Validate explicit tools input: enforce same pattern as extra_tools
          tools_trimmed="$(printf '%s' "${tools_raw}" | sed 's/^\s*//; s/\s*$//')"
          while IFS= read -r t; do
            t_trim="$(printf '%s' "${t}" | sed 's/^\s*//; s/\s*$//')"
            if [[ -z "${t_trim}" ]]; then
              continue
            fi
            if ! printf '%s' "${t_trim}" | grep -Eq '^[a-z0-9-]+$'; then
              v_error "invalid tool id in inputs.tools: ${t_trim} (allowed: lowercase letters, digits, hyphen)"
              exit 1
            fi
          done <<< "${tools_trimmed}"

          printf 'PS.TOOLS: using explicit tools input\n'
          printf 'PS.TOOLS_INPUT=%q\n' "${tools_raw}" >> "${GITHUB_ENV}"
          exit 0
        fi

        # Otherwise validate bundle enum and extra tools format
        require_enum "inputs.bundle" "${PS_BUNDLE_INPUT}" "lint" "security" "none" || exit 1

        # Extra tools can be empty; when provided ensure each id is lowercase letters, digits or hyphen
        extra_trimmed="$(printf '%s' "${PS_EXTRA_INPUT}" | sed 's/^\s*//; s/\s*$//')"

        # Early exit: if bundle=none and no extras provided, fail fast (saves runner time)
        if [[ "${PS_BUNDLE_INPUT}" == "none" && -z "${extra_trimmed}" ]]; then
          v_error "no tools selected (bundle=none and extra_tools empty). If you intended to provide explicit tools, use the 'tools' input."
          exit 1
        fi

        if [[ -n "${extra_trimmed}" ]]; then
          while IFS= read -r ex; do
            ex_trim="$(printf '%s' "${ex}" | sed 's/^\s*//; s/\s*$//')"
            if [[ -z "${ex_trim}" ]]; then
              continue
            fi
            if ! printf '%s' "${ex_trim}" | grep -Eq '^[a-z0-9-]+$'; then
              v_error "invalid tool id in inputs.extra_tools: ${ex_trim} (allowed: lowercase letters, digits, hyphen)"
              exit 1
            fi
          done <<< "${extra_trimmed}"
        fi

    - name: Assemble tool list
      shell: bash
      env:
        PS_BUNDLE_INPUT: ${{ inputs.bundle }}
        PS_EXTRA_INPUT: ${{ inputs.extra_tools }}
        PS_TOOLS_INPUT: ${{ inputs.tools }}
      run: |
        set -euo pipefail

        # If explicit `tools` provided, pass it through
        if [[ -n "${PS_TOOLS_INPUT:-}" ]]; then
          printf 'PS.TOOLS: using explicit tools input: %s\n' "${PS_TOOLS_INPUT}"
          printf 'PS_TOOLS=%s\n' "${PS_TOOLS_INPUT}" >> "${GITHUB_ENV}"
          exit 0
        fi

        tools_list=""
        if [[ "${PS_BUNDLE_INPUT}" == "lint" ]]; then
          tools_list=$'actionlint\nshellcheck\nhadolint\nyamllint'
        elif [[ "${PS_BUNDLE_INPUT}" == "security" ]]; then
          tools_list=$'gitleaks'
        fi

        # 3. Append Extras with deduplication
        PS_EXTRA_INPUT_TRIMMED="$(printf '%s' "${PS_EXTRA_INPUT}" | sed 's/^\s*//; s/\s*$//')"
        if [[ -n "${PS_EXTRA_INPUT_TRIMMED// }" ]]; then
          while IFS= read -r tool || [[ -n "${tool:-}" ]]; do
            tool_trim="$(printf '%s' "${tool}" | xargs)"
            [[ -z "${tool_trim}" ]] && continue

            # Use grep -F (fixed strings) and -x (exact line) for safety when checking duplicates
            if ! printf '%s\n' "${tools_list}" | grep -Fxq "${tool_trim}"; then
              tools_list="${tools_list:+$tools_list$'\n'}${tool_trim}"
            fi
          done <<< "${PS_EXTRA_INPUT_TRIMMED}"
        fi

        if [[ -z "${tools_list}" ]]; then
          v_error "no tools selected (bundle=none and extra_tools empty)"
          exit 1
        fi

        printf 'PS.TOOLS: final tools list:\n%s\n' "${tools_list}"
        printf 'PS_TOOLS=%s\n' "${tools_list}" >> "${GITHUB_ENV}"

    - name: Install tools (PS)
      uses: ./.github/actions/ps-install-tools
      with:
        install_dir: ${{ inputs.install_dir }}
        tools: ${{ env.PS_TOOLS }}

    - name: Run secrets scan (PS)
      if: ${{ inputs.run_security_scans == '1' }}
      uses: ./.github/actions/ps-preflight
      with:
        require_files: |
          tools/scripts/security/secret-scan-pr.sh

    - name: Run secrets scan (PS)
      if: ${{ inputs.run_security_scans == '1' }}
      uses: ./.github/actions/ps-run
      with:
        id: "secrets.fast"
        title: "Secrets scan (fast)"
        description: "Fast PR secret detection"
        script: "tools/scripts/security/secret-scan-pr.sh"

    - name: Done
      shell: bash
      run: |
        printf 'PS.TOOLS: OK\n'
