# =================================================================================================
# Political Sphere — Composite Action: Tools Installer (ps-tools)
# -------------------------------------------------------------------------------------------------
# Purpose:
#   Consolidate tool installation into a single canonical action. Supports predefined bundles
#   (`lint` and `security`) plus arbitrary `extra_tools` and also accepts an explicit `tools`
#   newline-separated list when callers have already assembled the list.
#
# Design:
#   - `bundle`: "lint" | "security" | "none" (default: none)
#   - `extra_tools`: optional newline-separated list of additional tool ids
#   - `tools`: optional newline-separated explicit tool list (takes precedence if provided)
#   - Internally delegates to `ps-install-tools` which performs pinned, SHA-verified installs
# Example:
#   bundle: "lint"
#
# Notes:
#   - Keeps behaviour deterministic and reuses existing installer logic
#   - Backwards compatible with callers that provide an explicit list via `tools`
# =================================================================================================

name: "PS Tools"
description: "Install pinned CLI tools (bundle + extra_tools) using the pinned installer"

inputs:
  install_dir:
    description: "Installation directory for CLI tools (repo-relative)"
    required: false
    default: ".tooling/bin"

  bundle:
    description: "Predefined tools bundle to install (lint, security, none)"
    required: false
    default: "none"

  extra_tools:
    description: "Optional newline-separated list of extra tool ids to install (one per line)"
    required: false
    default: ""

  tools:
    description: "Optional explicit newline-separated tool list to install (one id per line). If provided, this takes precedence over bundle/extra_tools."
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Resolve platform/workspace roots
      shell: bash
      run: |
        set -euo pipefail

        platform_root="${PS_PLATFORM_ROOT:-}"
        workspace_root="${GITHUB_WORKSPACE:-}"

        if [[ -n "${platform_root}" && -d "${platform_root}" ]]; then
          scripts_root="${platform_root}"
          printf 'PS.TOOLS: scripts_root=PS_PLATFORM_ROOT (%s)\n' "${scripts_root}"
        elif [[ -n "${workspace_root}" && -d "${workspace_root}" ]]; then
          scripts_root="${workspace_root}"
          printf 'PS.TOOLS: scripts_root=GITHUB_WORKSPACE (%s)\n' "${scripts_root}"
        else
          printf 'ERROR: neither PS_PLATFORM_ROOT nor GITHUB_WORKSPACE is available\n' >&2
          exit 1
        fi

        printf 'PS_SCRIPTS_ROOT=%s\n' "${scripts_root}" >> "${GITHUB_ENV}"

    - name: Validate inputs
      shell: bash
      env:
        PS_BUNDLE_INPUT: ${{ inputs.bundle }}
        PS_EXTRA_INPUT: ${{ inputs.extra_tools }}
        PS_TOOLS_INPUT: ${{ inputs.tools }}
      run: |
        set -euo pipefail

        scripts_root="${PS_SCRIPTS_ROOT:?PS_SCRIPTS_ROOT not set}"

        validate_sh="${scripts_root}/tools/scripts/branding/validate-inputs.sh"
        if [[ ! -f "${validate_sh}" ]]; then
          printf 'ERROR: validate-inputs.sh not found at %s\n' "${validate_sh}" >&2
          exit 1
        fi

        # shellcheck source=/dev/null
        . "${validate_sh}"

        # If explicit `tools` is provided, we accept it as authoritative
        tools_raw="${PS_TOOLS_INPUT:-}"
        if [[ -n "${tools_raw}" ]]; then
          require_nonempty "inputs.tools" "${tools_raw}" || exit 1
          printf 'PS.TOOLS: using explicit tools input\n'
          printf 'PS.TOOLS_INPUT=%q\n' "${tools_raw}" >> "${GITHUB_ENV}"
          exit 0
        fi

        # Otherwise validate bundle enum and extra tools format
        require_enum "inputs.bundle" "${PS_BUNDLE_INPUT}" "lint" "security" "none" || exit 1

        # Extra tools can be empty; when provided ensure each id is lowercase letters, digits or hyphen
        extra_trimmed="$(printf '%s' "${PS_EXTRA_INPUT}" | sed 's/^\s*//; s/\s*$//')"
        if [[ -n "${extra_trimmed}" ]]; then
          mapfile -t extras_arr <<< "${extra_trimmed}"
          for ex in "${extras_arr[@]}"; do
            ex_trim="$(printf '%s' "${ex}" | sed 's/^\s*//; s/\s*$//')"
            if [[ -z "${ex_trim}" ]]; then
              continue
            fi
            if ! printf '%s' "${ex_trim}" | grep -Eq '^[a-z0-9-]+$'; then
              v_error "invalid tool id in inputs.extra_tools: ${ex_trim} (allowed: lowercase letters, digits, hyphen)"
              exit 1
            fi
          done
        fi

    - name: Assemble tool list
      shell: bash
      env:
        PS_BUNDLE_INPUT: ${{ inputs.bundle }}
        PS_EXTRA_INPUT: ${{ inputs.extra_tools }}
        PS_TOOLS_INPUT: ${{ inputs.tools }}
      run: |
        set -euo pipefail

        # If explicit `tools` provided, pass it through
        if [[ -n "${PS_TOOLS_INPUT:-}" ]]; then
          printf 'PS.TOOLS: using explicit tools input: %s\n' "${PS_TOOLS_INPUT}"
          printf 'PS_TOOLS=%s\n' "${PS_TOOLS_INPUT}" >> "${GITHUB_ENV}"
          exit 0
        fi

        tools_list=""
        if [[ "${PS_BUNDLE_INPUT}" == "lint" ]]; then
          tools_list=$'actionlint\nshellcheck\nhadolint\nyamllint'
        elif [[ "${PS_BUNDLE_INPUT}" == "security" ]]; then
          tools_list=$'gitleaks'
        fi

        # Append extra_tools if present (newline-separated)
        PS_EXTRA_INPUT_TRIMMED="$(printf '%s' "${PS_EXTRA_INPUT}" | sed 's/^\s*//; s/\s*$//')"
        if [[ -n "${PS_EXTRA_INPUT_TRIMMED}" ]]; then
          mapfile -t extras_arr <<< "${PS_EXTRA_INPUT_TRIMMED}"
          for ex in "${extras_arr[@]}"; do
            ex_trim="$(printf '%s' "${ex}" | sed 's/^\s*//; s/\s*$//')"
            if [[ -z "${ex_trim}" ]]; then
              continue
            fi
            # avoid duplicates
            if ! printf '%s' "${tools_list}" | grep -Fxq "${ex_trim}"; then
              if [[ -n "${tools_list}" ]]; then
                tools_list+=$'\n'
              fi
              tools_list+="${ex_trim}"
            fi
          done
        fi

        if [[ -z "${tools_list}" ]]; then
          v_error "no tools selected (bundle=none and extra_tools empty)"
          exit 1
        fi

        printf 'PS.TOOLS: final tools list:\n%s\n' "${tools_list}"
        printf 'PS_TOOLS=%s\n' "${tools_list}" >> "${GITHUB_ENV}"

    - name: Install tools (PS)
      uses: ./.github/actions/ps-install-tools
      with:
        install_dir: ${{ inputs.install_dir }}
        tools: ${{ env.PS_TOOLS }}

    - name: Done
      shell: bash
      run: |
        printf 'PS.TOOLS: OK\n'
