# ==============================================================================
# Political Sphere — Composite Action: Checkout
# ------------------------------------------------------------------------------
# Purpose:
#   Checkout the repository with platform defaults and explicit inputs.
#
# Metadata:
#   - Created: 2025-12-20
#   - Last updated: 2025-12-20
#
# Scope & Responsibilities:
#   - Does: checkout a ref with controlled fetch depth.
#   - Does NOT: install dependencies or configure runtime environments.
#
# Design Principles:
#   - Deterministic and non-interactive execution
#   - Explicit inputs (no implicit defaults)
#   - SHA-pinned actions only
#
# Dependencies:
#   - actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
#   - tools/scripts/branding/validate-inputs.sh
#
# Dependents:
#   - ./.github/actions/ps-node-setup
#   - ./.github/workflows/security-scheduled.yml
#   - ./.github/workflows/release.yml
#
# Execution Model:
#   - Trigger: N/A (invoked by workflow steps)
#   - Type: composite action (internal-only)
#   - Invoked by: workflows and composite actions
#
# Security & Policy Notes:
#   - Secrets: none
#   - Permissions: inherited from the caller (contents: read expected)
#   - Constraints: fetch depth must be explicit for full-history scans
#
# Operational Notes:
#   - Timeouts: controlled by the calling job
#   - Artifacts: none
#   - CI vs local: identical behavior
# ==============================================================================

name: "PS Checkout"
description: "Checkout repository with platform defaults"

inputs:
  fetch_depth:
    description: "Git fetch depth (default: 1)"
    required: false
    default: "1"
  ref:
    description: "Optional ref to checkout"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Preflight (checkout)
      shell: bash
      env:
        PS_FETCH_DEPTH: ${{ inputs.fetch_depth }}
        PS_REF_INPUT: ${{ inputs.ref }}
      run: |
        set -euo pipefail

        depth="${PS_FETCH_DEPTH:-}"
        ref="${PS_REF_INPUT:-}"
        action_root="$(cd "${GITHUB_ACTION_PATH}/../../.." >/dev/null 2>&1 && pwd)"
        platform_root="${PS_PLATFORM_ROOT:-}"
        if [[ -n "${platform_root}" && -d "${platform_root}" ]]; then
          echo "PS.CHECKOUT: using PS_PLATFORM_ROOT=${platform_root}"
        else
          platform_root="${action_root}"
        fi
        validate_sh="${platform_root}/tools/scripts/branding/validate-inputs.sh"
        if [[ ! -f "${validate_sh}" ]]; then
          echo "ERROR: validate-inputs.sh not found at ${validate_sh}" >&2
          exit 1
        fi
        # shellcheck source=tools/scripts/branding/validate-inputs.sh
        . "${validate_sh}"

        require_number "fetch_depth" "${depth}"

        echo "PS.CHECKOUT: fetch_depth=${depth}"
        if [[ -n "${ref}" ]]; then
          echo "PS.CHECKOUT: ref=${ref}"
        else
          echo "PS.CHECKOUT: ref=<default>"
        fi

    - name: Checkout
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
      with:
        fetch-depth: ${{ inputs.fetch_depth }}
        ref: ${{ inputs.ref }}

    - name: Checkout complete
      shell: bash
      run: |
        echo "PS.CHECKOUT: OK"
