# ==============================================================================
# Political Sphere — Composite Action: Setup (Runner + Node)
# ------------------------------------------------------------------------------
# Purpose:
#   Combine runner hardening and Node.js setup into a single step.
#
# Metadata:
#   - Created: 2025-12-20
#   - Last updated: 2025-12-20
#
# Scope & Responsibilities:
#   - Does: harden the runner, checkout code, setup Node.js, optionally install deps.
#   - Does NOT: run build/test scripts or change job permissions.
#
# Design Principles:
#   - Deterministic and non-interactive execution
#   - Explicit inputs with safe defaults
#   - SHA-pinned actions only
#
# Dependencies:
#   - ./.github/actions/ps-harden-runner
#   - ./.github/actions/ps-node-setup
#
# Dependents:
#   - (Optional) workflows that want a single setup step
#
# Execution Model:
#   - Trigger: N/A (invoked by workflow steps)
#   - Type: composite action (internal-only)
#
# Security & Policy Notes:
#   - Secrets: optional NODE_AUTH_TOKEN is inherited from the caller
#   - Permissions: inherited from the caller
#
# Operational Notes:
#   - Timeouts: controlled by the calling job
#   - Artifacts: none
# ==============================================================================

name: "PS Setup"
description: "Harden runner and setup Node.js with platform defaults"

inputs:
  node_version:
    description: "Node.js major version"
    required: false
    default: "22"
  ref:
    description: "Optional checkout ref forwarded to ps-node-setup"
    required: false
    default: ""
  fetch_depth:
    description: "Git fetch depth (1 = shallow, 0 = full history)"
    required: false
    default: "1"
  skip_checkout:
    description: "Skip checkout when repo is already present (1 = skip, 0 = run)"
    required: false
    default: "0"
  cache:
    description: "Enable dependency caching in ps-node-bootstrap (1 = on, 0 = off)"
    required: false
    default: "1"
  install_dependencies:
    description: "Run npm ci in ps-node-bootstrap (1 = on, 0 = off)"
    required: false
    default: "1"
  skip_harden:
    description: "Skip the built-in runner hardening step (1 = skip, 0 = run). Use when calling step-security/harden-runner from the workflow to ensure pre/post hooks run correctly."
    required: false
    default: "0"

runs:
  using: "composite"
  steps:
    - name: Harden runner (PS)
      if: ${{ inputs.skip_harden != '1' }}
      uses: ./.github/actions/ps-harden-runner

    - name: Setup summary (PS)
      shell: bash
      env:
        PS_NODE_VERSION: ${{ inputs.node_version }}
        PS_FETCH_DEPTH: ${{ inputs.fetch_depth }}
        PS_REF_INPUT: ${{ inputs.ref }}
        PS_CACHE: ${{ inputs.cache }}
        PS_INSTALL_DEPS: ${{ inputs.install_dependencies }}
      run: |
        set -euo pipefail
        echo "PS.SETUP: node_version=${PS_NODE_VERSION}"
        echo "PS.SETUP: fetch_depth=${PS_FETCH_DEPTH}"
        if [[ -n "${PS_REF_INPUT}" ]]; then
          echo "PS.SETUP: ref=${PS_REF_INPUT}"
        else
          echo "PS.SETUP: ref=<default>"
        fi
        echo "PS.SETUP: cache=${PS_CACHE}"
        echo "PS.SETUP: install_dependencies=${PS_INSTALL_DEPS}"

    - name: Node setup (PS)
      uses: ./.github/actions/ps-node-setup
      with:
        node_version: ${{ inputs.node_version }}
        ref: ${{ inputs.ref }}
        fetch_depth: ${{ inputs.fetch_depth }}
        skip_checkout: ${{ inputs.skip_checkout }}
        cache: ${{ inputs.cache }}
        install_dependencies: ${{ inputs.install_dependencies }}

    - name: Setup complete
      shell: bash
      run: |
        echo "PS.SETUP: OK"
