# ==============================================================================
# Political Sphere — Composite Action: Install Tools
# ------------------------------------------------------------------------------
# Purpose:
#   Install pinned CLI tools using the shared tooling installer.
#
# Metadata:
#   - Created: 2025-12-20
#   - Last updated: 2025-12-20
#
# Scope & Responsibilities:
#   - Does: validate tool list and install requested tools.
#   - Does NOT: run lint/security scans or modify permissions.
#
# Design Principles:
#   - Deterministic, pinned versions + SHA256 verification
#   - Non-interactive execution
#   - Explicit inputs with strict validation
#
# Dependencies:
#   - configs/security/tooling.env
#   - tools/scripts/ci/install-tools.sh
#   - tools/scripts/branding/validate-inputs.sh
#   - curl, tar, sha256sum, python3 (runner-provided)
#
# Dependents:
#   - ./.github/actions/ps-lint-tools
#   - ./.github/actions/ps-security-tools
#
# Execution Model:
#   - Trigger: N/A (invoked by workflow steps)
#   - Type: composite action (internal-only)
#
# Security & Policy Notes:
#   - Secrets: none
#   - Permissions: inherited from the caller
#   - Constraints: Linux-only (GitHub-hosted ubuntu runners)
#
# Operational Notes:
#   - Timeouts: controlled by the calling job
#   - Artifacts: none
#   - CI vs local: designed for CI usage only
# ==============================================================================

name: "PS Install Tools"
description: "Install pinned CLI tools via the shared tooling installer"

inputs:
  install_dir:
    description: "Installation directory for CLI tools (repo-relative)"
    required: false
    default: ".tooling/bin"

  tools:
    description: "Comma-separated tool list (actionlint,shellcheck,hadolint,yamllint,gitleaks,trivy)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Resolve platform/workspace roots
      shell: bash
      run: |
        set -euo pipefail

        platform_root="${PS_PLATFORM_ROOT:-}"
        workspace_root="${GITHUB_WORKSPACE:-}"

        if [[ -n "${platform_root}" && -d "${platform_root}" ]]; then
          scripts_root="${platform_root}"
          printf 'PS.INSTALL_TOOLS: scripts_root=PS_PLATFORM_ROOT (%s)\n' "${scripts_root}"
        elif [[ -n "${workspace_root}" && -d "${workspace_root}" ]]; then
          scripts_root="${workspace_root}"
          printf 'PS.INSTALL_TOOLS: scripts_root=GITHUB_WORKSPACE (%s)\n' "${scripts_root}"
        else
          printf 'ERROR: neither PS_PLATFORM_ROOT nor GITHUB_WORKSPACE is available\n' >&2
          exit 1
        fi

        printf 'PS_SCRIPTS_ROOT=%s\n' "${scripts_root}" >> "${GITHUB_ENV}"

    - name: Validate inputs
      shell: bash
      env:
        PS_TOOLS_RAW: ${{ inputs.tools }}
        PS_INSTALL_DIR_INPUT: ${{ inputs.install_dir }}
      run: |
        set -euo pipefail

        scripts_root="${PS_SCRIPTS_ROOT:?PS_SCRIPTS_ROOT not set}"

        validate_sh="${scripts_root}/tools/scripts/branding/validate-inputs.sh"
        if [[ ! -f "${validate_sh}" ]]; then
          printf 'ERROR: validate-inputs.sh not found at %s\n' "${validate_sh}" >&2
          exit 1
        fi
        
        # shellcheck source=/dev/null
        . "${validate_sh}"

        tools_raw="${PS_TOOLS_RAW:-}"
        install_dir="${PS_INSTALL_DIR_INPUT:-}"

        require_nonempty "inputs.tools" "${tools_raw}" || exit 1
        require_regex \
          "inputs.tools" \
          "${tools_raw}" \
          '^[a-z0-9,-]+$' \
          "Allowed: lowercase letters, digits, comma, hyphen." || exit 1

        # install_dir must be a safe repo-relative path (no absolute, no traversal)
        require_nonempty "inputs.install_dir" "${install_dir}" || exit 1
        if [[ "${install_dir}" == /* ]]; then
          v_error "inputs.install_dir must be repo-relative (must not start with /)"
          exit 1
        fi
        if [[ "${install_dir}" == *".."* ]]; then
          v_error "inputs.install_dir must not contain '..' path traversal"
          exit 1
        fi

        # Parse and validate tool list (trim whitespace defensively)
        IFS=',' read -r -a tools_arr <<< "${tools_raw}"
        if [[ "${#tools_arr[@]}" -eq 0 ]]; then
          v_error "inputs.tools must include at least one tool name"
          exit 1
        fi

        for tool in "${tools_arr[@]}"; do
          tool="$(printf '%s' "${tool}" | xargs)"
            exit 1
          fi
          require_enum \
            "tool" \
            "${tool}" \
            actionlint shellcheck hadolint yamllint gitleaks trivy || exit 1
        done

        printf 'PS.INSTALL_TOOLS: install_dir=%q\n' "$install_dir"
        printf 'PS.INSTALL_TOOLS: tools=%q\n' "$tools_raw"

    - name: Install tools (pinned)
      shell: bash
      env:
        PS_TOOLS_RAW: ${{ inputs.tools }}
        PS_INSTALL_DIR_INPUT: ${{ inputs.install_dir }}
      run: |
        set -euo pipefail

        scripts_root="${PS_SCRIPTS_ROOT:?PS_SCRIPTS_ROOT not set}"

        installer="${scripts_root}/tools/scripts/ci/install-tools.sh"
        if [[ ! -f "${installer}" ]]; then
          printf 'ERROR: install-tools.sh not found at %s\n' "${installer}" >&2
          exit 1
        fi

        tools_raw="${PS_TOOLS_RAW:-}"
        IFS=',' read -r -a tools_arr <<< "${tools_raw}"

        export PS_INSTALL_DIR="${GITHUB_WORKSPACE}/${PS_INSTALL_DIR_INPUT}"
        mkdir -p "${PS_INSTALL_DIR}"

        bash "${installer}" "${tools_arr[@]}"

        echo "PS.INSTALL_TOOLS: OK"
