# ==============================================================================
# Political Sphere — Composite Action: Install Tools
# ------------------------------------------------------------------------------
# Purpose:
#   Install pinned CLI tools using the shared tooling installer.
#
# Metadata:
#   - Created: 2025-12-20
#   - Last updated: 2025-12-20
#
# Scope & Responsibilities:
#   - Does: validate tool list and install requested tools.
#   - Does NOT: run lint/security scans or modify permissions.
#
# Design Principles:
#   - Deterministic, pinned versions + SHA256 verification
#   - Non-interactive execution
#   - Explicit inputs with strict validation
#
# Dependencies:
#   - configs/security/tooling.env
#   - tools/scripts/ci/install-tools.sh
#   - tools/scripts/branding/validate-inputs.sh
#   - curl, tar, sha256sum, python3 (runner-provided)
#
# Dependents:
#   - ./.github/actions/ps-lint-tools
#   - ./.github/actions/ps-security-tools
#
# Execution Model:
#   - Trigger: N/A (invoked by workflow steps)
#   - Type: composite action (internal-only)
#
# Security & Policy Notes:
#   - Secrets: none
#   - Permissions: inherited from the caller
#   - Constraints: Linux-only (GitHub-hosted ubuntu runners)
#
# Operational Notes:
#   - Timeouts: controlled by the calling job
#   - Artifacts: none
#   - CI vs local: designed for CI usage only
# ==============================================================================

name: "PS Install Tools"
description: "Install pinned CLI tools via the shared tooling installer"

inputs:
  install_dir:
    description: "Installation directory for CLI tools (repo-relative)"
    required: false
    default: ".tooling/bin"

  tools:
    description: "Comma-separated tool list (actionlint,shellcheck,hadolint,yamllint,gitleaks,trivy)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Validate tools input
      shell: bash
      run: |
        set -euo pipefail
        action_root="$(cd "${GITHUB_ACTION_PATH}/../../.." >/dev/null 2>&1 && pwd)"
        validate_sh="${action_root}/tools/scripts/branding/validate-inputs.sh"
        if [[ ! -f "${validate_sh}" ]]; then
          echo "ERROR: validate-inputs.sh not found at ${validate_sh}" >&2
          exit 1
        fi
        # shellcheck source=tools/scripts/branding/validate-inputs.sh
        . "${validate_sh}"

        tools_raw="${{ inputs.tools }}"
        require_nonempty "inputs.tools" "${tools_raw}" || exit 1
        require_regex \
          "inputs.tools" \
          "${tools_raw}" \
          '^[a-z0-9,-]+$' \
          "Allowed: lowercase letters, digits, comma, hyphen." || exit 1

        IFS=',' read -r -a tools_arr <<< "${tools_raw}"
        if [[ "${#tools_arr[@]}" -eq 0 ]]; then
          v_error "inputs.tools must include at least one tool name"
          exit 1
        fi

        for tool in "${tools_arr[@]}"; do
          tool="$(echo "${tool}" | xargs)"
          if [[ -z "${tool}" ]]; then
            v_error "inputs.tools contains an empty tool name"
            exit 1
          fi
          require_enum \
            "tool" \
            "${tool}" \
            actionlint shellcheck hadolint yamllint gitleaks trivy || exit 1
        done

    - name: Install tools (pinned)
      shell: bash
      run: |
        set -euo pipefail

        tools_raw="${{ inputs.tools }}"
        IFS=',' read -r -a tools_arr <<< "${tools_raw}"

        export PS_INSTALL_DIR="${GITHUB_WORKSPACE}/${{ inputs.install_dir }}"
        bash "${GITHUB_WORKSPACE}/tools/scripts/ci/install-tools.sh" "${tools_arr[@]}"
