# ==============================================================================
# Political Sphere — Composite Action: Semgrep CLI (SARIF)
# ------------------------------------------------------------------------------
# Purpose:
#   Run Semgrep CLI and publish SARIF to GitHub code scanning.
#
# Metadata:
#   - Created: 2025-12-20
#   - Last updated: 2025-12-20
#
# Scope & Responsibilities:
#   - Does: install Semgrep, scan, upload SARIF, enforce exit policy.
#   - Does NOT: manage CodeQL or dependency scanning.
#
# Design Principles:
#   - Deterministic version pinning
#   - Non-interactive execution (no prompts/telemetry)
#   - CI-safe SARIF upload
#
# Dependencies:
#   - python3 + pip (runner-provided)
#   - github/codeql-action/upload-sarif@7c9a7896f03bb1f3de14c5663ed46759e27443e0
#   - Semgrep CLI (installed from PyPI)
#   - tools/scripts/branding/validate-inputs.sh
#
# Dependents:
#   - ./.github/workflows/security-scheduled.yml
#
# Execution Model:
#   - Trigger: N/A (invoked by workflow steps)
#   - Type: composite action (internal-only)
#   - Invoked by: security workflows
#
# Security & Policy Notes:
#   - Secrets: none
#   - Permissions: requires security-events: write in the calling job
#   - Constraints: SARIF must be uploaded even when findings exist
#
# Operational Notes:
#   - Timeouts: controlled by the calling job
#   - Artifacts: produces SARIF at inputs.output
#   - CI vs local: identical behavior
# ==============================================================================

name: "Semgrep CLI (SARIF)"
description: "Run Semgrep via CLI and upload SARIF to code scanning"

inputs:
  version:
    description: "Pinned Semgrep version to install (e.g. 1.461.0)"
    required: true

  config:
    description: "Semgrep config (e.g. p/ci or a local config path)"
    required: false
    default: "p/ci"

  path:
    description: "Scan path (relative to repo root)"
    required: false
    default: "."

  output:
    description: "SARIF output file path"
    required: false
    default: "reports/semgrep/semgrep.sarif"

  fail_on_findings:
    description: "If true, fail when Semgrep reports findings (exit 1)"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Validate inputs
      shell: bash
      env:
        SEMGREP_VERSION_INPUT: ${{ inputs.version }}
        SEMGREP_FAIL_ON_FINDINGS_INPUT: ${{ inputs.fail_on_findings }}
        SEMGREP_OUTPUT_INPUT: ${{ inputs.output }}
        SEMGREP_CONFIG_INPUT: ${{ inputs.config }}
        SEMGREP_PATH_INPUT: ${{ inputs.path }}
      run: |
        set -euo pipefail

        # Resolve platform root deterministically.
        platform_root="${PS_PLATFORM_ROOT:-${GITHUB_WORKSPACE}/.ps-platform}"
        if [[ ! -d "${platform_root}" ]]; then
          echo "ERROR: platform_root not found: ${platform_root}" >&2
          echo "HINT: export PS_PLATFORM_ROOT or checkout platform into .ps-platform." >&2
          exit 1
        fi

        validate_sh="${platform_root}/tools/scripts/branding/validate-inputs.sh"
        if [[ ! -f "${validate_sh}" ]]; then
          echo "ERROR: validate-inputs.sh not found at ${validate_sh}" >&2
          exit 1
        fi
        # shellcheck source=/dev/null
        . "${validate_sh}"

        version="${SEMGREP_VERSION_INPUT:-}"
        fail_on_findings="${SEMGREP_FAIL_ON_FINDINGS_INPUT:-}"

        require_nonempty "inputs.version" "${version}" || exit 1
        require_regex \
          "inputs.version" \
          "${version}" \
          '^[0-9]+\.[0-9]+\.[0-9]+$' \
          "Use a pinned SemVer like 1.461.0." || exit 1

        require_enum "inputs.fail_on_findings" "${fail_on_findings}" true false || exit 1

        # Basic output sanity (avoid empty / weird values).
        out="${SEMGREP_OUTPUT_INPUT:-}"
        require_nonempty "inputs.output" "${out}" || exit 1

        echo "PS.SEMGREP: version=${version}"
        echo "PS.SEMGREP: config=${SEMGREP_CONFIG_INPUT:-}"
        echo "PS.SEMGREP: path=${SEMGREP_PATH_INPUT:-}"
        echo "PS.SEMGREP: output=${out}"
        echo "PS.SEMGREP: fail_on_findings=${fail_on_findings}"

    - name: Install Semgrep (pinned, venv)
      shell: bash
      env:
        SEMGREP_VERSION_INPUT: ${{ inputs.version }}
      run: |
        set -euo pipefail

        if ! command -v python3 >/dev/null 2>&1; then
          echo "ERROR: python3 is required to install Semgrep." >&2
          exit 1
        fi

        venv_dir="${GITHUB_WORKSPACE}/.tooling/venv/semgrep"
        mkdir -p "$(dirname "${venv_dir}")"
        python3 -m venv "${venv_dir}"

        # shellcheck source=/dev/null
        source "${venv_dir}/bin/activate"

        python3 -m pip install --disable-pip-version-check --no-input --no-cache-dir \
          "semgrep==${SEMGREP_VERSION_INPUT}"

        semgrep --version

    - name: Run Semgrep (produce SARIF)
      shell: bash
      env:
        SEMGREP_SEND_METRICS: "off"
        SEMGREP_OUTPUT_INPUT: ${{ inputs.output }}
        SEMGREP_CONFIG_INPUT: ${{ inputs.config }}
        SEMGREP_PATH_INPUT: ${{ inputs.path }}
      run: |
        set -euo pipefail

        # shellcheck source=/dev/null
        source "${GITHUB_WORKSPACE}/.tooling/venv/semgrep/bin/activate"

        out="${SEMGREP_OUTPUT_INPUT:-}"
        out_dir="$(dirname "${out}")"
        mkdir -p "${out_dir}"

        semgrep_exit=0
        semgrep \
          --metrics=off \
          --config="${SEMGREP_CONFIG_INPUT:-}" \
          --sarif \
          --output "${out}" \
          "${SEMGREP_PATH_INPUT:-}" \
          || semgrep_exit=$?

        # Semgrep exit codes:
        # 0 = no findings
        # 1 = findings
        # >1 = error
        echo "${semgrep_exit}" > "${GITHUB_WORKSPACE}/.semgrep-exit-code.txt"

        if [[ ! -f "${out}" ]]; then
          echo "ERROR: SARIF output not found at '${out}'." >&2
          echo "HINT: semgrep exited with code ${semgrep_exit} and did not produce SARIF." >&2
          exit 1
        fi

        echo "PS.SEMGREP: sarif=${out}"
        echo "PS.SEMGREP: exit=${semgrep_exit}"

    - name: Upload SARIF to code scanning
      # NOTE: Ensure this SHA is valid upstream; your validate-ci is correctly failing when it isn't.
      uses: github/codeql-action/upload-sarif@7c9a7896f03bb1f3de14c5663ed46759e27443e0
      with:
        sarif_file: ${{ inputs.output }}

    - name: Enforce Semgrep outcome
      shell: bash
      env:
        SEMGREP_FAIL_ON_FINDINGS_INPUT: ${{ inputs.fail_on_findings }}
      run: |
        set -euo pipefail

        semgrep_exit="$(cat "${GITHUB_WORKSPACE}/.semgrep-exit-code.txt" 2>/dev/null || echo 2)"

        if [[ "${semgrep_exit}" -gt 1 ]]; then
          echo "ERROR: Semgrep failed with exit code ${semgrep_exit}." >&2
          exit "${semgrep_exit}"
        fi

        if [[ "${semgrep_exit}" -eq 1 && "${SEMGREP_FAIL_ON_FINDINGS_INPUT:-}" == "true" ]]; then
          echo "ERROR: Semgrep reported findings (exit 1)." >&2
          exit 1
        fi

        echo "PS.SEMGREP: completed (exit ${semgrep_exit})."
        echo "PS.SEMGREP: OK"
