# ==============================================================================
# Political Sphere — Composite Action: License Compliance
# License: Proprietary
# ==============================================================================
# ps_header_v: 6
#
# ─────────────────────────────────────────────────────────────────────────────
# IDENTITY
# ─────────────────────────────────────────────────────────────────────────────
# meta:
#   file_id: .github/actions/ps-task/license-check/action.yml
#   file_type: action
#   language: yaml
#   version: 1.0.0
#   status: active
#   classification: internal
#   owner: political-sphere
#   last_editor: codex
#
# ─────────────────────────────────────────────────────────────────────────────
# LIFECYCLE & CHANGE CONTROL
# ─────────────────────────────────────────────────────────────────────────────
#   lifecycle:
#     created: 2025-12-28
#     last_updated: 2025-12-28
#     last_updated_mode: manual
#     review_cycle: 6 months
#     change_control: lightweight
#
# ─────────────────────────────────────────────────────────────────────────────
# CONTEXT
# ─────────────────────────────────────────────────────────────────────────────
# context:
#   parent_system: CI/CD Platform
#   initiative: Hardened CI
#
# ─────────────────────────────────────────────────────────────────────────────
# GOVERNANCE
# ─────────────────────────────────────────────────────────────────────────────
# governance:
#   intent: Provide the License Compliance composite action to Check dependency
#     licenses against the platform policy.
#   guarantees:
#     - Defines inputs and outputs for consistent downstream usage.
#     - Executes the composite steps declared in this action.
#     - Uses pinned external actions when referenced.
#   prohibitions:
#     - Does not grant permissions beyond the invoking workflow.
#     - Does not assume network access beyond runner policy.
#
# ─────────────────────────────────────────────────────────────────────────────
# INTERFACES
# ─────────────────────────────────────────────────────────────────────────────
# interfaces:
#   inputs: [policy_path, lock_path, report_dir, log_dir]
#   outputs: [status, report_path, log_path]
#   exit_codes: [0=success, 1=failure]
#
# ─────────────────────────────────────────────────────────────────────────────
# EXECUTION
# ─────────────────────────────────────────────────────────────────────────────
# execution:
#   invocation: Used as a composite action step in GitHub Actions workflows.
#   example_invocation: >-
#     uses: ./.github/actions/ps-task/license-check
#   model: deterministic
#   idempotency: not guaranteed
#
# ─────────────────────────────────────────────────────────────────────────────
# DEPENDENCIES
# ─────────────────────────────────────────────────────────────────────────────
# dependencies:
#   internal: [configs/security/license-policy.yml, tools/scripts/security/license-check.sh]
#   external: [bash]
#
# ─────────────────────────────────────────────────────────────────────────────
# SECURITY & POLICY
# ─────────────────────────────────────────────────────────────────────────────
# security:
#   permissions: [none]
#   secrets: [none]
#   network: restricted; depends on runner policy
#   policy_enforcement: [configs/ci/policies/allowed-actions.yml,
#     configs/ci/policies/action-pinning.yml,
#     configs/ci/policies/inline-bash.yml,
#     configs/ci/policies/section-headers.yml]
#
# ─────────────────────────────────────────────────────────────────────────────
# OPERATIONS
# ─────────────────────────────────────────────────────────────────────────────
# ops:
#   failure_modes: Step failures or validation errors surface as non-zero exits.
#   observability: Step logs are emitted in the GitHub Actions job output.
#   performance: Seconds to minutes depending on repo size and workload.
#
# ─────────────────────────────────────────────────────────────────────────────
# RISKS
# ─────────────────────────────────────────────────────────────────────────────
# risks:
#   assumptions:
#     - Inputs are provided as documented.
#     - Runner has required tooling for declared steps.
#   known_risks:
#     - Network or platform outages can interrupt execution.
#
# ─────────────────────────────────────────────────────────────────────────────
# RELATED
# ─────────────────────────────────────────────────────────────────────────────
# related:
#   references:
#     - .github/actions/ps-task/license-check/README.md
#     - configs/security/license-policy.yml
#     - tools/scripts/security/license-check.sh
#
# ==============================================================================

name: "License Compliance"
description: "Check dependency licenses against the platform policy"

inputs:
  policy_path:
    description: "Path to license policy (repo-relative)"
    required: false
    default: "configs/security/license-policy.yml"

  lock_path:
    description: "Dependency lockfile path (repo-relative)"
    required: false
    default: "package-lock.json"

  report_dir:
    description: "Report output directory (repo-relative)"
    required: false
    default: "reports/security"

  log_dir:
    description: "Log output directory (repo-relative)"
    required: false
    default: "logs/security"

outputs:
  status:
    description: "Task status (success|failure)"
    value: ${{ steps.license.outputs.status }}

  report_path:
    description: "Task report JSON path"
    value: ${{ steps.license.outputs.report_path }}

  log_path:
    description: "Task log path"
    value: ${{ steps.license.outputs.log_path }}

runs:
  using: "composite"
  steps:
    - name: Prepare output directories (PS)
      shell: bash
      env:
        PS_REPORT_DIR_INPUT: ${{ inputs.report_dir }}
        PS_LOG_DIR_INPUT: ${{ inputs.log_dir }}
      run: |
        set -euo pipefail
        for d in "${PS_REPORT_DIR_INPUT}" "${PS_LOG_DIR_INPUT}"; do
          [[ -n "${d}" ]] || { echo "ERROR: output dir empty" >&2; exit 1; }
          if [[ "${d}" == /* || "${d}" == *".."* ]]; then
            echo "ERROR: unsafe dir path: ${d}" >&2
            exit 1
          fi
          mkdir -p "${GITHUB_WORKSPACE}/${d}"
        done

    - name: License compliance (PS)
      id: license
      uses: ./.github/actions/ps-task/ps-run
      with:
        id: "security.license"
        title: "License compliance"
        description: "Policy-driven OSS license validation"
        script: "tools/scripts/security/license-check.sh"
        require_files: |
          tools/scripts/security/license-check.sh
          ${{ inputs.policy_path }}
          ${{ inputs.lock_path }}
        artifact_paths: |
          ${{ inputs.report_dir }}
          ${{ inputs.log_dir }}
        env_kv: |
          PS_LICENSE_POLICY=${{ inputs.policy_path }}
          PS_LICENSE_LOCK_PATH=${{ inputs.lock_path }}
          PS_REPORT_DIR=${{ inputs.report_dir }}
          PS_LOG_DIR=${{ inputs.log_dir }}

    - name: Complete (PS)
      shell: bash
      run: |
        set -euo pipefail
        printf 'PS.TASK.LICENSE_CHECK: OK\n'
