# ==============================================================================
# Political Sphere — Composite Action: License Compliance
# ==============================================================================
#
# PURPOSE
# ------------------------------------------------------------------------------
# Enforce OSS license compliance using a policy file + dependency lockfile, and
# emit evidence (reports/logs) in a deterministic, CI-safe manner.
#
# ==============================================================================
name: "License Compliance"
description: "Check dependency licenses against the platform policy"

inputs:
  policy_path:
    description: "Path to license policy (repo-relative)"
    required: false
    default: "configs/security/license-policy.yml"

  lock_path:
    description: "Dependency lockfile path (repo-relative)"
    required: false
    default: "package-lock.json"

  report_dir:
    description: "Report output directory (repo-relative)"
    required: false
    default: "reports/security"

  log_dir:
    description: "Log output directory (repo-relative)"
    required: false
    default: "logs/security"

outputs:
  status:
    description: "Task status (success|failure)"
    value: ${{ steps.license.outputs.status }}

  report_path:
    description: "Task report JSON path"
    value: ${{ steps.license.outputs.report_path }}

  log_path:
    description: "Task log path"
    value: ${{ steps.license.outputs.log_path }}

runs:
  using: "composite"
  steps:
    - name: Prepare output directories (PS)
      shell: bash
      env:
        PS_REPORT_DIR_INPUT: ${{ inputs.report_dir }}
        PS_LOG_DIR_INPUT: ${{ inputs.log_dir }}
      run: |
        set -euo pipefail
        for d in "${PS_REPORT_DIR_INPUT}" "${PS_LOG_DIR_INPUT}"; do
          [[ -n "${d}" ]] || { echo "ERROR: output dir empty" >&2; exit 1; }
          [[ "${d}" == /* || "${d}" == *".."* ]] && { echo "ERROR: unsafe dir path: ${d}" >&2; exit 1; }
          mkdir -p "${GITHUB_WORKSPACE}/${d}"
        done

    - name: License compliance (PS)
      id: license
      uses: ./.github/actions/ps-task/ps-run
      with:
        id: "security.license"
        title: "License compliance"
        description: "Policy-driven OSS license validation"
        script: "tools/scripts/security/license-check.sh"
        require_files: |
          tools/scripts/security/license-check.sh
          ${{ inputs.policy_path }}
          ${{ inputs.lock_path }}
        artifact_paths: |
          ${{ inputs.report_dir }}
          ${{ inputs.log_dir }}
        env_kv: |
          PS_LICENSE_POLICY=${{ inputs.policy_path }}
          PS_LICENSE_LOCK_PATH=${{ inputs.lock_path }}
          PS_REPORT_DIR=${{ inputs.report_dir }}
          PS_LOG_DIR=${{ inputs.log_dir }}
