# ==============================================================================
# Political Sphere - Composite Action: License Compliance
# ------------------------------------------------------------------------------
# Purpose:
#   Enforce OSS license compliance using the platform policy and lockfile.
#
# Metadata:
#   - Created: 2025-12-20
#   - Last updated: 2025-12-20
#
# Scope & Responsibilities:
#   - Does: run the license compliance script and emit reports/logs.
#   - Does NOT: install dependencies or alter permissions.
#
# Design Principles:
#   - Deterministic and non-interactive execution
#   - Policy-driven allowlist/denylist logic
#   - CI-safe, structured outputs
#
# Dependencies:
#   - ./.github/actions/ps-task/ps-run
#   - tools/scripts/security/license-check.sh
#   - configs/security/license-policy.yml
#
# Dependents:
#   - ./.github/workflows/license-compliance.yml
#
# Execution Model:
#   - Trigger: N/A (invoked by workflow steps)
#   - Type: composite action (internal-only)
#
# Security & Policy Notes:
#   - Secrets: none
#   - Permissions: inherited from the caller (read-only expected)
#
# Operational Notes:
#   - Timeouts: controlled by the calling job
#   - Artifacts: reports/** and logs/** emitted by the script
#   - CI vs local: requires policy + lockfile in CI
# ==============================================================================

name: "License Compliance"
description: "Check dependency licenses against the platform policy"

inputs:
  policy_path:
    description: "Path to license policy (repo-relative)"
    required: false
    default: "configs/security/license-policy.yml"
  lock_path:
    description: "Path to package-lock.json (repo-relative)"
    required: false
    default: "package-lock.json"
  report_dir:
    description: "Report output directory (repo-relative)"
    required: false
    default: "reports/security"
  log_dir:
    description: "Log output directory (repo-relative)"
    required: false
    default: "logs/security"

runs:
  using: "composite"
  steps:
    - name: License compliance (PS)
      uses: ./.github/actions/ps-task/ps-run
      with:
        id: "security.license"
        title: "License compliance"
        description: "Policy-driven OSS license validation"
        script: "tools/scripts/security/license-check.sh"
        require_files: |
          tools/scripts/security/license-check.sh
          ${{ inputs.policy_path }}
          ${{ inputs.lock_path }}
        env_kv: |
          PS_LICENSE_POLICY=${{ inputs.policy_path }}
          PS_LICENSE_LOCK_PATH=${{ inputs.lock_path }}
          PS_REPORT_DIR=${{ inputs.report_dir }}
          PS_LOG_DIR=${{ inputs.log_dir }}
