# ==============================================================================
# Political Sphere — Composite Action: PS Upload Artifacts
# License: Proprietary
# ==============================================================================
# ps_header_v: 6
#
# ─────────────────────────────────────────────────────────────────────────────
# IDENTITY
# ─────────────────────────────────────────────────────────────────────────────
# meta:
#   file_id: .github/actions/ps-teardown/ps-upload-build-artifacts/action.yml
#   file_type: action
#   language: yaml
#   version: 1.0.0
#   status: active
#   classification: internal
#   owner: political-sphere
#   last_editor: codex
#
# ─────────────────────────────────────────────────────────────────────────────
# LIFECYCLE & CHANGE CONTROL
# ─────────────────────────────────────────────────────────────────────────────
#   lifecycle:
#     created: 2025-12-28
#     last_updated: 2025-12-28
#     last_updated_mode: manual
#     review_cycle: 6 months
#     change_control: lightweight
#
# ─────────────────────────────────────────────────────────────────────────────
# CONTEXT
# ─────────────────────────────────────────────────────────────────────────────
# context:
#   parent_system: CI/CD Platform
#   initiative: Hardened CI
#
# ─────────────────────────────────────────────────────────────────────────────
# GOVERNANCE
# ─────────────────────────────────────────────────────────────────────────────
# governance:
#   intent: Provide the PS Upload Artifacts composite action to Upload workflow
#     artifacts with platform defaults.
#   guarantees:
#     - Defines inputs and outputs for consistent downstream usage.
#     - Executes the composite steps declared in this action.
#     - Uses pinned external actions when referenced.
#   prohibitions:
#     - Does not grant permissions beyond the invoking workflow.
#     - Does not assume network access beyond runner policy.
#
# ─────────────────────────────────────────────────────────────────────────────
# INTERFACES
# ─────────────────────────────────────────────────────────────────────────────
# interfaces:
#   inputs: [name, path, retention_days, if_no_files_found, compression_level]
#   outputs: [none]
#   exit_codes: [0=success, 1=failure]
#
# ─────────────────────────────────────────────────────────────────────────────
# EXECUTION
# ─────────────────────────────────────────────────────────────────────────────
# execution:
#   invocation: Used as a composite action step in GitHub Actions workflows.
#   example_invocation: >-
#     uses: ./.github/actions/ps-teardown/ps-upload-build-artifacts
#   model: deterministic
#   idempotency: not guaranteed
#
# ─────────────────────────────────────────────────────────────────────────────
# DEPENDENCIES
# ─────────────────────────────────────────────────────────────────────────────
# dependencies:
#   internal: [tools/scripts/actions/ps-teardown]
#   external: [bash, actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f]
#
# ─────────────────────────────────────────────────────────────────────────────
# SECURITY & POLICY
# ─────────────────────────────────────────────────────────────────────────────
# security:
#   permissions: [none]
#   secrets: [none]
#   network: restricted; depends on runner policy
#   policy_enforcement: [configs/ci/policies/allowed-actions.yml,
#     configs/ci/policies/action-pinning.yml,
#     configs/ci/policies/inline-bash.yml,
#     configs/ci/policies/section-headers.yml]
#
# ─────────────────────────────────────────────────────────────────────────────
# OPERATIONS
# ─────────────────────────────────────────────────────────────────────────────
# ops:
#   failure_modes: Step failures or validation errors surface as non-zero exits.
#   observability: Step logs are emitted in the GitHub Actions job output.
#   performance: Seconds to minutes depending on repo size and workload.
#
# ─────────────────────────────────────────────────────────────────────────────
# RISKS
# ─────────────────────────────────────────────────────────────────────────────
# risks:
#   assumptions:
#     - Inputs are provided as documented.
#     - Runner has required tooling for declared steps.
#   known_risks:
#     - Network or platform outages can interrupt execution.
#
# ─────────────────────────────────────────────────────────────────────────────
# RELATED
# ─────────────────────────────────────────────────────────────────────────────
# related:
#   references:
#     - tools/scripts/actions/ps-teardown
#
# ==============================================================================

name: "PS Upload Artifacts"
description: "Upload workflow artifacts with platform defaults"

inputs:
  name:
    description: "Artifact name (must be CI-safe)"
    required: true

  path:
    description: "Paths to upload (newline-separated globs supported)"
    required: true

  retention_days:
    description: "Retention days (positive integer)"
    required: false
    default: "7"

  if_no_files_found:
    description: "Behavior when no files are found: warn | error | ignore"
    required: false
    default: "warn"

  compression_level:
    description: "Zlib compression level (0-9)"
    required: false
    default: "6"

runs:
  using: "composite"
  steps:
    - name: Validate inputs (PS)
      shell: bash
      env:
        PS_NAME: ${{ inputs.name }}
        PS_RETENTION: ${{ inputs.retention_days }}
        PS_NOFILES: ${{ inputs.if_no_files_found }}
        PS_PATHS: ${{ inputs.path }}
        PS_COMPRESSION_LEVEL: ${{ inputs.compression_level }}
      run: |
        validate_root="${GITHUB_ACTION_PATH}/../../../tools/scripts/actions/ps-teardown"
        validate_root="${validate_root}/ps-upload-artifacts"
        validate_script="${validate_root}/ps-upload-artifacts-validate.sh"
        bash "${validate_script}"
    - name: Upload artifacts
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f  # v6.0.0
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
        retention-days: ${{ inputs.retention_days }}
        if-no-files-found: ${{ inputs.if_no_files_found }}
        compression-level: ${{ inputs.compression_level }}

    - name: Complete (PS)
      shell: bash
      run: |
        set -euo pipefail
        printf 'PS.TEARDOWN.UPLOAD_ARTIFACTS: OK\n'
