# ==============================================================================
# Political Sphere — Composite Action: Semgrep CLI (SARIF)
# License: Proprietary
# ==============================================================================
# ps_header_v: 6
#
# ─────────────────────────────────────────────────────────────────────────────
# IDENTITY
# ─────────────────────────────────────────────────────────────────────────────
# meta:
#   file_id: .github/actions/ps-task/semgrep-cli/action.yml
#   file_type: action
#   language: yaml
#   version: 1.0.0
#   status: active
#   classification: internal
#   owner: political-sphere
#   last_editor: codex
#
# ─────────────────────────────────────────────────────────────────────────────
# LIFECYCLE & CHANGE CONTROL
# ─────────────────────────────────────────────────────────────────────────────
#   lifecycle:
#     created: 2025-12-28
#     last_updated: 2025-12-28
#     last_updated_mode: manual
#     review_cycle: 6 months
#     change_control: lightweight
#
# ─────────────────────────────────────────────────────────────────────────────
# CONTEXT
# ─────────────────────────────────────────────────────────────────────────────
# context:
#   parent_system: CI/CD Platform
#   initiative: Hardened CI
#
# ─────────────────────────────────────────────────────────────────────────────
# GOVERNANCE
# ─────────────────────────────────────────────────────────────────────────────
# governance:
#   intent: Provide the Semgrep CLI (SARIF) composite action to Run Semgrep via CLI
#     and upload SARIF to code scanning.
#   guarantees:
#     - Defines inputs and outputs for consistent downstream usage.
#     - Executes the composite steps declared in this action.
#     - Uses pinned external actions when referenced.
#   prohibitions:
#     - Does not grant permissions beyond the invoking workflow.
#     - Does not assume network access beyond runner policy.
#
# ─────────────────────────────────────────────────────────────────────────────
# INTERFACES
# ─────────────────────────────────────────────────────────────────────────────
# interfaces:
#   inputs: [version, config, path, output, semgrep_sha256, semgrep_allow_unverified,
#     fail_on_findings]
#   outputs: [none]
#   exit_codes: [0=success, 1=failure]
#
# ─────────────────────────────────────────────────────────────────────────────
# EXECUTION
# ─────────────────────────────────────────────────────────────────────────────
# execution:
#   invocation: Used as a composite action step in GitHub Actions workflows.
#   example_invocation: >-
#     uses: ./.github/actions/ps-task/semgrep-cli
#   model: deterministic
#   idempotency: not guaranteed
#
# ─────────────────────────────────────────────────────────────────────────────
# DEPENDENCIES
# ─────────────────────────────────────────────────────────────────────────────
# dependencies:
#   internal: [tools/scripts/security/semgrep-cli.sh,
#     tools/scripts/security/semgrep-validate-inputs.sh,
#     tools/scripts/security/semgrep-install.sh,
#     tools/scripts/security/semgrep-scan.sh,
#     tools/scripts/security/semgrep-enforce.sh]
#   external: [none]
#
# ─────────────────────────────────────────────────────────────────────────────
# SECURITY & POLICY
# ─────────────────────────────────────────────────────────────────────────────
# security:
#   permissions: [none]
#   secrets: [none]
#   network: restricted; depends on runner policy
#   policy_enforcement: [configs/ci/policies/allowed-actions.yml,
#     configs/ci/policies/action-pinning.yml,
#     configs/ci/policies/inline-bash.yml,
#     configs/ci/policies/section-headers.yml]
#
# ─────────────────────────────────────────────────────────────────────────────
# OPERATIONS
# ─────────────────────────────────────────────────────────────────────────────
# ops:
#   failure_modes: Step failures or validation errors surface as non-zero exits.
#   observability: Step logs are emitted in the GitHub Actions job output.
#   performance: Seconds to minutes depending on repo size and workload.
#
# ─────────────────────────────────────────────────────────────────────────────
# RISKS
# ─────────────────────────────────────────────────────────────────────────────
# risks:
#   assumptions:
#     - Inputs are provided as documented.
#     - Runner has required tooling for declared steps.
#   known_risks:
#     - Network or platform outages can interrupt execution.
#
# ─────────────────────────────────────────────────────────────────────────────
# RELATED
# ─────────────────────────────────────────────────────────────────────────────
# related:
#   references:
#     - .github/actions/ps-task/semgrep-cli/README.md
#     - tools/scripts/security/semgrep-cli.sh
#     - tools/scripts/security/semgrep-validate-inputs.sh
#     - tools/scripts/security/semgrep-install.sh
#     - tools/scripts/security/semgrep-scan.sh
#     - tools/scripts/security/semgrep-enforce.sh
#
# ==============================================================================

name: "Semgrep CLI (SARIF)"
description: "Run Semgrep via CLI and upload SARIF to code scanning"

inputs:
  version:
    description: "Pinned Semgrep version to install (e.g. 1.461.0)"
    required: true

  config:
    description: "Semgrep config (e.g. p/ci or a local config path)"
    required: false
    default: "p/ci"

  path:
    description: "Scan path (relative to repo root)"
    required: false
    default: "."

  output:
    description: "SARIF output file path"
    required: false
    default: "reports/semgrep/semgrep.sarif"

  semgrep_sha256:
    description: "Optional SHA-256 checksum for the Semgrep package artifact"
    required: false
    default: ""

  semgrep_allow_unverified:
    description: "Allow Semgrep install without checksum (true|false)"
    required: false
    default: "false"

  fail_on_findings:
    description: "If true, fail when Semgrep reports findings (exit 1)"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Run Semgrep (PS)
      uses: ./.github/actions/ps-task/ps-run
      with:
        id: "security.semgrep"
        title: "Semgrep CLI"
        description: "Run Semgrep and upload SARIF"
        script: "tools/scripts/security/semgrep-cli.sh"
        require_files: |
          tools/scripts/security/semgrep-cli.sh
          tools/scripts/security/semgrep-validate-inputs.sh
          tools/scripts/security/semgrep-install.sh
          tools/scripts/security/semgrep-scan.sh
          tools/scripts/security/semgrep-enforce.sh
        artifact_paths: |
          ${{ inputs.output }}
        env_kv: |
          SEMGREP_VERSION=${{ inputs.version }}
          SEMGREP_CONFIG=${{ inputs.config }}
          SEMGREP_PATH=${{ inputs.path }}
          SEMGREP_OUTPUT=${{ inputs.output }}
          SEMGREP_SHA256=${{ inputs.semgrep_sha256 }}
          SEMGREP_ALLOW_UNVERIFIED=${{ inputs.semgrep_allow_unverified }}
          SEMGREP_FAIL_ON_FINDINGS=${{ inputs.fail_on_findings }}

    - name: Complete (PS)
      shell: bash
      run: |
        set -euo pipefail
        printf 'PS.TASK.SEMGREP_CLI: OK\n'
