# ==============================================================================
# Political Sphere — Composite Action: Harden Runner
# ------------------------------------------------------------------------------
# Purpose:
#   Apply runner hardening with Political Sphere defaults.
#
# Key behaviours:
#   - Validates inputs deterministically
#   - Works with split "platform repo" checkout via PS_PLATFORM_ROOT
#   - Avoids accidental overriding of allowed-endpoints when empty
#   - Mitigates harden-runner post-step ENOENT by ensuring /home/agent exists
# ==============================================================================

name: "PS Harden Runner"
description: "Harden GitHub runner with Political Sphere defaults"

inputs:
  egress_policy:
    description: >
      Egress policy passed through to step-security/harden-runner.
      Allowed values: audit | block
      Default: audit
    required: false
    default: "audit"

  allowed_endpoints:
    description: >
      Optional allowlist of endpoints for block mode.
      Format: newline-separated hostnames or host:port entries.
      Leave empty to not set allowed-endpoints (avoid accidental overrides).
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Validate inputs
      shell: bash
      env:
        PS_EGRESS_POLICY_INPUT: ${{ inputs.egress_policy }}
        PS_ALLOWED_ENDPOINTS_INPUT: ${{ inputs.allowed_endpoints }}
      run: |
        set -euo pipefail

        # Prefer platform root when provided (split checkout), otherwise fall back
        # to resolving a repo root relative to this action.
        platform_root="${PS_PLATFORM_ROOT:-}"
        if [[ -z "${platform_root}" || ! -d "${platform_root}" ]]; then
          platform_root="$(cd "${GITHUB_ACTION_PATH}/../../.." >/dev/null 2>&1 && pwd)"
        fi

        validate_sh="${platform_root}/tools/scripts/branding/validate-inputs.sh"
        if [[ ! -f "${validate_sh}" ]]; then
          echo "ERROR: validate-inputs.sh not found at ${validate_sh}" >&2
          echo "HINT: set PS_PLATFORM_ROOT to the platform repo root (e.g. .ps-platform)." >&2
          exit 1
        fi

        # shellcheck source=/dev/null
        . "${validate_sh}"

        policy="$(echo "${PS_EGRESS_POLICY_INPUT:-}" | tr '[:upper:]' '[:lower:]' | xargs)"
        require_enum "inputs.egress_policy" "${policy}" audit block || exit 1

        # Warn (not fail) if block mode has no allowlist.
        if [[ "${policy}" == "block" ]]; then
          if [[ -z "$(echo "${PS_ALLOWED_ENDPOINTS_INPUT:-}" | xargs)" ]]; then
            echo "WARN: egress_policy=block but allowed_endpoints is empty; network access may be restricted." >&2
          fi
        fi

        echo "PS_EGRESS_POLICY=${policy}" >> "${GITHUB_ENV}"
        echo "PS.HARDEN_RUNNER: egress_policy=${policy}"
        if [[ -n "$(echo "${PS_ALLOWED_ENDPOINTS_INPUT:-}" | xargs)" ]]; then
          echo "PS.HARDEN_RUNNER: allowed_endpoints=provided"
        else
          echo "PS.HARDEN_RUNNER: allowed_endpoints=empty"
        fi

    - name: Ensure harden-runner post path exists
      shell: bash
      run: |
        set -euo pipefail
        # harden-runner post step may write to /home/agent/post_event.json on some runners
        if command -v sudo >/dev/null 2>&1; then
          sudo mkdir -p /home/agent
          # keep perms reasonable but writable
          sudo chmod 0775 /home/agent || true
        else
          mkdir -p /home/agent || true
          chmod 0775 /home/agent || true
        fi

    # IMPORTANT: do not pass allowed-endpoints when empty (avoid accidental overrides)
    - name: Harden runner (no allowlist)
      if: ${{ inputs.allowed_endpoints == '' }}
      uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.1.4
      with:
        egress-policy: ${{ env.PS_EGRESS_POLICY }}

    - name: Harden runner (with allowlist)
      if: ${{ inputs.allowed_endpoints != '' }}
      uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.1.4
      with:
        egress-policy: ${{ env.PS_EGRESS_POLICY }}
        allowed-endpoints: ${{ inputs.allowed_endpoints }}

    - name: Harden runner complete
      shell: bash
      run: |
        set -euo pipefail
        echo "PS.HARDEN_RUNNER: OK"
