# ==============================================================================
# Political Sphere — Composite Action: Consumer Contract
# License: Proprietary
# ==============================================================================
# ps_header_v: 6
#
# ─────────────────────────────────────────────────────────────────────────────
# IDENTITY
# ─────────────────────────────────────────────────────────────────────────────
# meta:
#   file_id: .github/actions/ps-task/consumer-contract/action.yml
#   file_type: action
#   language: yaml
#   version: 1.0.0
#   status: active
#   classification: internal
#   owner: political-sphere
#   last_editor: codex
#
# ─────────────────────────────────────────────────────────────────────────────
# LIFECYCLE & CHANGE CONTROL
# ─────────────────────────────────────────────────────────────────────────────
#   lifecycle:
#     created: 2025-12-28
#     last_updated: 2025-12-28
#     last_updated_mode: manual
#     review_cycle: 6 months
#     change_control: lightweight
#
# ─────────────────────────────────────────────────────────────────────────────
# CONTEXT
# ─────────────────────────────────────────────────────────────────────────────
# context:
#   parent_system: CI/CD Platform
#   initiative: Hardened CI
#
# ─────────────────────────────────────────────────────────────────────────────
# GOVERNANCE
# ─────────────────────────────────────────────────────────────────────────────
# governance:
#   intent: Provide the Consumer Contract composite action to Validate consumer
#     repositories against the platform contract policy.
#   guarantees:
#     - Defines inputs and outputs for consistent downstream usage.
#     - Executes the composite steps declared in this action.
#     - Uses pinned external actions when referenced.
#   prohibitions:
#     - Does not grant permissions beyond the invoking workflow.
#     - Does not assume network access beyond runner policy.
#
# ─────────────────────────────────────────────────────────────────────────────
# INTERFACES
# ─────────────────────────────────────────────────────────────────────────────
# interfaces:
#   inputs: [policy_path, exceptions_path, report_path, summary_path, baseline_path, log_dir]
#   outputs: [none]
#   exit_codes: [0=success, 1=failure]
#
# ─────────────────────────────────────────────────────────────────────────────
# EXECUTION
# ─────────────────────────────────────────────────────────────────────────────
# execution:
#   invocation: Used as a composite action step in GitHub Actions workflows.
#   example_invocation: >-
#     uses: ./.github/actions/ps-task/consumer-contract
#   model: deterministic
#   idempotency: not guaranteed
#
# ─────────────────────────────────────────────────────────────────────────────
# DEPENDENCIES
# ─────────────────────────────────────────────────────────────────────────────
# dependencies:
#   internal: [configs/consumer/contract.json, configs/consumer/exceptions.json,
#     tools/scripts/consumer/contract-check.sh]
#   external: [bash]
#
# ─────────────────────────────────────────────────────────────────────────────
# SECURITY & POLICY
# ─────────────────────────────────────────────────────────────────────────────
# security:
#   permissions: [none]
#   secrets: [none]
#   network: restricted; depends on runner policy
#   policy_enforcement: [configs/ci/policies/allowed-actions.yml,
#     configs/ci/policies/action-pinning.yml,
#     configs/ci/policies/inline-bash.yml,
#     configs/ci/policies/section-headers.yml]
#
# ─────────────────────────────────────────────────────────────────────────────
# OPERATIONS
# ─────────────────────────────────────────────────────────────────────────────
# ops:
#   failure_modes: Step failures or validation errors surface as non-zero exits.
#   observability: Step logs are emitted in the GitHub Actions job output.
#   performance: Seconds to minutes depending on repo size and workload.
#
# ─────────────────────────────────────────────────────────────────────────────
# RISKS
# ─────────────────────────────────────────────────────────────────────────────
# risks:
#   assumptions:
#     - Inputs are provided as documented.
#     - Runner has required tooling for declared steps.
#   known_risks:
#     - Network or platform outages can interrupt execution.
#
# ─────────────────────────────────────────────────────────────────────────────
# RELATED
# ─────────────────────────────────────────────────────────────────────────────
# related:
#   references:
#     - .github/actions/ps-task/consumer-contract/README.md
#     - configs/consumer/contract.json
#     - configs/consumer/exceptions.json
#     - tools/scripts/consumer/contract-check.sh
#
# ==============================================================================

name: "Consumer Contract"
description: "Validate consumer repositories against the platform contract policy"

inputs:
  policy_path:
    description: "Contract policy path (repo-relative)"
    required: false
    default: "configs/consumer/contract.json"
  exceptions_path:
    description: "Exceptions policy path (repo-relative)"
    required: false
    default: "configs/consumer/exceptions.json"
  report_path:
    description: "Report output path (repo-relative)"
    required: false
    default: "reports/contracts/contract.json"
  summary_path:
    description: "Summary output path (repo-relative)"
    required: false
    default: "reports/contracts/contract.txt"
  baseline_path:
    description: "Baseline report path for drift detection (repo-relative)"
    required: false
    default: ""
  log_dir:
    description: "Log output directory (repo-relative)"
    required: false
    default: "logs/contracts"

runs:
  using: "composite"
  steps:
    - name: Contract check (PS)
      uses: ./.github/actions/ps-task/ps-run
      with:
        id: "contract.check"
        title: "Consumer contract"
        description: "Validate repo contract vs policy"
        script: "tools/scripts/consumer/contract-check.sh"
        require_files: |
          tools/scripts/consumer/contract-check.sh
          ${{ inputs.policy_path }}
        env_kv: |
          PS_CONTRACT_POLICY=${{ inputs.policy_path }}
          PS_CONTRACT_EXCEPTIONS=${{ inputs.exceptions_path }}
          PS_CONTRACT_REPORT=${{ inputs.report_path }}
          PS_CONTRACT_SUMMARY=${{ inputs.summary_path }}
          PS_CONTRACT_BASELINE=${{ inputs.baseline_path }}
          PS_LOG_DIR=${{ inputs.log_dir }}
    - name: Contract summary (PS)
      shell: bash
      env:
        SUMMARY_PATH: "${{ inputs.summary_path }}"
      run: |
        # Protect against unsafe user-controlled paths: ensure repo-relative,
        # no traversal or absolute paths
        summary_path="${SUMMARY_PATH:-}"
        if [[ -z "${summary_path}" ]]; then
          exit 0
        fi
        if [[ "${summary_path}" = /* ]] || [[ "${summary_path}" == *".."* ]]; then
          echo "WARN: summary_path appears unsafe or contains traversal," \
            "skipping: ${summary_path}" >&2
          exit 0
        fi
        if [[ -f "${summary_path}" && -n "${GITHUB_STEP_SUMMARY:-}" ]]; then
          # Use explicit -- to avoid filename starting with '-'
          cat -- "${summary_path}" >> "${GITHUB_STEP_SUMMARY}"
        fi

    - name: Complete (PS)
      shell: bash
      run: |
        set -euo pipefail
        printf 'PS.TASK.CONSUMER_CONTRACT: OK\n'
