# ==============================================================================
# Political Sphere — Example Consumer Workflow: PR Gates
# ------------------------------------------------------------------------------
# Purpose:
#   Demonstrate how a consumer repository calls the reusable PR gates workflow.
#
# Notes:
#   - Replace org/repo and version with your actual platform repository.
#   - Set least-privilege permissions appropriate to your repo.
# ==============================================================================

name: PR Gates (Consumer Example)

on:
  pull_request:

permissions:
  contents: read

jobs:
  pr-gates:
    uses: org/ps-cicd-platform/.github/workflows/pr-gates.yml@vX.Y.Z
    permissions:
      contents: read
    with:
      pr_number: ${{ github.event.pull_request.number }}
      pr_is_fork: ${{ github.event.pull_request.head.repo.fork }}
      pr_base_ref: ${{ github.event.pull_request.base.sha }}
      pr_head_ref: ${{ github.event.pull_request.head.sha }}
