# ==============================================================================
# Political Sphere — Composite Action: CI Validate
# ==============================================================================
#
# METADATA
# ------------------------------------------------------------------------------
# id: ci-validate
# version: 1.1.0
# owner: political-sphere
# classification: internal
# created: 2025-12-20
# last_updated: 2025-12-26
#
# DEPENDENCIES
# ------------------------------------------------------------------------------
# - tools/scripts/ci/validate-ci-action.sh
#
# DEPENDENTS
# ------------------------------------------------------------------------------
# - Workflow jobs that run ci-validate
#
#
# PURPOSE
# ------------------------------------------------------------------------------
# Run the Validate-CI policy gate using the checked-out platform repository.
# This action is intentionally strict: it will fail fast if required paths are
# missing or misconfigured.
#
#
# GUARANTEES
# ------------------------------------------------------------------------------
# - Deterministic, non-interactive execution
# - Clear diagnostics on missing/invalid inputs
# - No secret printing (no env dumps)
# - Stable telemetry markers for logs
#
#
# REQUIREMENTS
# ------------------------------------------------------------------------------
# - The platform repository must already be checked out.
# - The platform root must be provided either via:
#     - inputs.platform_root, OR
#     - env.PS_PLATFORM_ROOT
#
# ==============================================================================
name: "CI Validate"
description: "Runs the Validate-CI policy gate (Political Sphere)"

inputs:
  platform_root:
    description: "Absolute path to platform checkout directory. Defaults to env.PS_PLATFORM_ROOT."
    required: false
    default: ""

  script_relpath:
    description: "Script path relative to the repository root."
    required: false
    default: "tools/scripts/ci/validate-ci-action.sh"

outputs:
  platform_root:
    description: "Resolved platform root used for validation"
    value: ${{ steps.resolve.outputs.platform_root }}

runs:
  using: "composite"
  steps:
    - name: Resolve & validate inputs (PS)
      id: resolve
      shell: bash
      env:
        PS_PLATFORM_ROOT_INPUT: ${{ inputs.platform_root }}
        PS_PLATFORM_ROOT_ENV: ${{ env.PS_PLATFORM_ROOT }}
        PS_SCRIPT_RELPATH: ${{ inputs.script_relpath }}
      run: |
        set -euo pipefail

        # Resolve platform root: prefer explicit input, else env.
        platform_root="${PS_PLATFORM_ROOT_INPUT:-}"
        if [[ -z "${platform_root}" ]]; then
          platform_root="${PS_PLATFORM_ROOT_ENV:-}"
        fi

        if [[ -z "${platform_root}" ]]; then
          printf 'ERROR: CI Validate requires platform root.\n' >&2
          printf 'Set inputs.platform_root or env.PS_PLATFORM_ROOT (e.g. %s/.ps-platform).\n' \
            "${GITHUB_WORKSPACE}" >&2
          exit 1
        fi

        # Require an absolute path (prevents ambiguity + path traversal).
        if [[ "${platform_root}" != /* ]]; then
          printf 'ERROR: platform_root must be an absolute path (got %q)\n' "${platform_root}" >&2
          exit 1
        fi

        if [[ ! -d "${platform_root}" ]]; then
          printf 'ERROR: platform_root directory not found: %q\n' "${platform_root}" >&2
          exit 1
        fi

        script_rel="${PS_SCRIPT_RELPATH:-tools/scripts/ci/validate-ci-action.sh}"
        if [[ -z "${script_rel}" ]]; then
          printf 'ERROR: inputs.script_relpath must not be empty\n' >&2
          exit 1
        fi

        # Script is expected to live in the *repo*, not the platform repo.
        # That keeps Validate-CI runnable regardless of platform structure.
        script_abs="${GITHUB_WORKSPACE}/${script_rel}"
        if [[ ! -f "${script_abs}" ]]; then
          printf 'ERROR: Validate-CI script not found at %q\n' "${script_abs}" >&2
          printf 'Expected relative path: %q\n' "${script_rel}" >&2
          exit 1
        fi

        printf 'PS.CI_VALIDATE: platform_root=%s\n' "${platform_root}"
        printf 'PS.CI_VALIDATE: script=%s\n' "${script_abs}"

        emit_output() {
          local key="$1"
          local val="$2"
          local sanitized delimiter attempts
          sanitized="${val//$'\r'/}"
          delimiter="__PS_OUT_${RANDOM}_${RANDOM}__"
          attempts=0
          while [[ "${sanitized}" == *"${delimiter}"* ]]; do
            attempts=$((attempts + 1))
            if [[ "${attempts}" -gt 6 ]]; then
              printf 'ERROR: output value for %s contains an unsafe heredoc delimiter\n' \
                "${key}" >&2
              exit 1
            fi
            delimiter="__PS_OUT_${RANDOM}_${RANDOM}__"
          done
          printf '%s<<%s\n%s\n%s\n' \
            "${key}" "${delimiter}" "${sanitized}" "${delimiter}" \
            >> "${GITHUB_OUTPUT}"
        }

        emit_output "platform_root" "${platform_root}"
        emit_output "script_abs" "${script_abs}"

    - name: Run Validate-CI gate (PS)
      shell: bash
      env:
        PS_PLATFORM_ROOT: ${{ steps.resolve.outputs.platform_root }}
        PS_VALIDATE_SCRIPT_ABS: ${{ steps.resolve.outputs.script_abs }}
      run: |
        set -euo pipefail
        script="${PS_VALIDATE_SCRIPT_ABS}"

        format_sh="${GITHUB_WORKSPACE}/tools/scripts/branding/format.sh"
        if [[ -f "${format_sh}" ]]; then
          # shellcheck source=/dev/null
          . "${format_sh}"
          if type -t ps_header >/dev/null 2>&1; then
            ps_header "Policy Gate: CI Validation"
          fi
        fi

        # Ensure executable bit isn't required (CI runners can run via bash).
        bash "${script}"

    - name: CI Validate complete (PS)
      shell: bash
      run: |
        set -euo pipefail
        printf 'PS.CI_VALIDATE: OK\n'
