# ==============================================================================
# Political Sphere — Composite Action: PS Teardown (Switchboard)
# ------------------------------------------------------------------------------
# Purpose:
#   Canonical teardown switchboard for end-of-job reporting and cleanup.
# ==============================================================================

name: "PS Teardown"
description: "Canonical job teardown switchboard: summary, artifacts, optional PR comment"

inputs:
  summary_workflow:
    description: "Workflow identifier for the summary payload (optional)"
    required: false
    default: ""

  summary_output_path:
    description: "Output path for the summary JSON (repo-relative, optional)"
    required: false
    default: ""

  summary_results:
    description: "Newline-separated key=value result pairs (optional)"
    required: false
    default: ""

  artifacts_name:
    description: "Artifact name to upload (optional)"
    required: false
    default: ""

  artifacts_paths:
    description: "Paths to upload (newline-separated globs, optional)"
    required: false
    default: ""

  artifacts_retention_days:
    description: "Artifact retention days (optional)"
    required: false
    default: "7"

  artifacts_if_no_files_found:
    description: "Behavior when no files are found: warn | error | ignore"
    required: false
    default: "warn"

  artifacts_compression_level:
    description: "Zlib compression level (0-9)"
    required: false
    default: "6"

  pr_number:
    description: "Optional PR number to comment on"
    required: false
    default: ""

  github_token:
    description: "Token for posting PR comments (issues: write)"
    required: false
    default: ""

  pr_comment_body:
    description: "Optional PR comment body (markdown)"
    required: false
    default: ""

  pr_comment_body_path:
    description: "Optional path to PR comment body file (repo-relative)"
    required: false
    default: ""

  pr_comment_body_prefix:
    description: "Optional prefix for PR comment body when using pr_comment_body_path"
    required: false
    default: ""

  pr_comment_body_suffix:
    description: "Optional suffix for PR comment body when using pr_comment_body_path"
    required: false
    default: ""

  expected_base_sha:
    description: "Optional expected base SHA for PR comment validation"
    required: false
    default: ""

  expected_head_sha:
    description: "Optional expected head SHA for PR comment validation"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Resolve inputs (PS)
      id: ps_teardown_inputs
      shell: bash
      env:
        PS_SUMMARY_WORKFLOW: ${{ inputs.summary_workflow }}
        PS_SUMMARY_OUTPUT_PATH: ${{ inputs.summary_output_path }}
        PS_SUMMARY_RESULTS: ${{ inputs.summary_results }}
        PS_ARTIFACTS_NAME: ${{ inputs.artifacts_name }}
        PS_ARTIFACTS_PATHS: ${{ inputs.artifacts_paths }}
        PS_PR_NUMBER: ${{ inputs.pr_number }}
        PS_GITHUB_TOKEN: ${{ inputs.github_token }}
        PS_PR_BODY: ${{ inputs.pr_comment_body }}
        PS_PR_BODY_PATH: ${{ inputs.pr_comment_body_path }}
        PS_PR_BODY_PREFIX: ${{ inputs.pr_comment_body_prefix }}
        PS_PR_BODY_SUFFIX: ${{ inputs.pr_comment_body_suffix }}
      run: |
        set -euo pipefail

        trim() {
          local s="$1"
          s="${s#"${s%%[![:space:]]*}"}"
          s="${s%"${s##*[![:space:]]}"}"
          printf '%s' "${s}"
        }

        emit_output() {
          local key="$1"
          local val="$2"
          local sanitized delimiter attempts
          sanitized="${val//$'\r'/}"
          delimiter="__PS_OUT_${RANDOM}_${RANDOM}__"
          attempts=0
          while [[ "${sanitized}" == *"${delimiter}"* ]]; do
            attempts=$((attempts + 1))
            if [[ "${attempts}" -gt 6 ]]; then
              echo "ERROR: output value for ${key} contains an unsafe heredoc delimiter" >&2
              exit 1
            fi
            delimiter="__PS_OUT_${RANDOM}_${RANDOM}__"
          done
          printf '%s<<%s\n%s\n%s\n' "${key}" "${delimiter}" "${sanitized}" "${delimiter}" >> "${GITHUB_OUTPUT}"
        }

        summary_workflow="$(trim "${PS_SUMMARY_WORKFLOW}")"
        summary_output_path="$(trim "${PS_SUMMARY_OUTPUT_PATH}")"
        summary_results="$(trim "${PS_SUMMARY_RESULTS}")"
        artifacts_name="$(trim "${PS_ARTIFACTS_NAME}")"
        artifacts_paths="$(trim "${PS_ARTIFACTS_PATHS}")"
        pr_number="$(trim "${PS_PR_NUMBER}")"
        github_token="$(trim "${PS_GITHUB_TOKEN}")"
        pr_body="$(trim "${PS_PR_BODY}")"
        pr_body_path="$(trim "${PS_PR_BODY_PATH}")"
        pr_body_prefix="${PS_PR_BODY_PREFIX:-}"
        pr_body_suffix="${PS_PR_BODY_SUFFIX:-}"

        run_summary="0"
        if [[ -n "${summary_workflow}" || -n "${summary_output_path}" || -n "${summary_results}" ]]; then
          if [[ -z "${summary_workflow}" || -z "${summary_output_path}" || -z "${summary_results}" ]]; then
            echo "ERROR: summary_workflow, summary_output_path, and summary_results must be provided together." >&2
            exit 1
          fi
          run_summary="1"
        fi

        run_artifacts="0"
        if [[ -n "${artifacts_name}" || -n "${artifacts_paths}" ]]; then
          if [[ -z "${artifacts_name}" || -z "${artifacts_paths}" ]]; then
            echo "ERROR: artifacts_name and artifacts_paths must be provided together." >&2
            exit 1
          fi
          run_artifacts="1"
        fi

        run_pr_comment="0"
        if [[ -n "${pr_number}" || -n "${github_token}" || -n "${pr_body}" ]]; then
          if [[ -z "${pr_number}" || -z "${github_token}" ]]; then
            echo "ERROR: pr_number and github_token are required to post a PR comment." >&2
            exit 1
          fi
          run_pr_comment="1"
        fi

        if [[ -z "${pr_body}" && -n "${pr_body_path}" ]]; then
          if [[ "${pr_body_path}" == /* || "${pr_body_path}" == *".."* ]]; then
            echo "ERROR: pr_comment_body_path must be repo-relative and must not include '..'." >&2
            exit 1
          fi
          body_file="${GITHUB_WORKSPACE}/${pr_body_path}"
          if [[ ! -f "${body_file}" ]]; then
            echo "ERROR: pr_comment_body_path not found: ${body_file}" >&2
            exit 1
          fi
          pr_body="${pr_body_prefix}$(cat "${body_file}")${pr_body_suffix}"
        fi

        if [[ -z "${pr_body}" ]]; then
          if [[ -n "${summary_workflow}" ]]; then
            pr_body="Automated CI teardown report for workflow \`${summary_workflow}\`."
          else
            pr_body="Automated CI teardown report."
          fi
        fi

        emit_output "run_summary" "${run_summary}"
        emit_output "run_artifacts" "${run_artifacts}"
        emit_output "run_pr_comment" "${run_pr_comment}"
        emit_output "pr_body" "${pr_body}"

    - name: Write summary (PS)
      if: ${{ steps.ps_teardown_inputs.outputs.run_summary == '1' }}
      uses: ./.github/actions/ps-write-summary
      with:
        workflow: ${{ inputs.summary_workflow }}
        output_path: ${{ inputs.summary_output_path }}
        results: ${{ inputs.summary_results }}

    - name: Upload artifacts (PS)
      if: ${{ steps.ps_teardown_inputs.outputs.run_artifacts == '1' }}
      uses: ./.github/actions/ps-upload-artifacts
      with:
        name: ${{ inputs.artifacts_name }}
        path: ${{ inputs.artifacts_paths }}
        retention_days: ${{ inputs.artifacts_retention_days }}
        if_no_files_found: ${{ inputs.artifacts_if_no_files_found }}
        compression_level: ${{ inputs.artifacts_compression_level }}

    - name: Post PR comment (PS)
      if: ${{ steps.ps_teardown_inputs.outputs.run_pr_comment == '1' }}
      uses: ./.github/actions/ps-pr-comment
      with:
        pr_number: ${{ inputs.pr_number }}
        body: ${{ steps.ps_teardown_inputs.outputs.pr_body }}
        github_token: ${{ inputs.github_token }}
        expected_base_sha: ${{ inputs.expected_base_sha }}
        expected_head_sha: ${{ inputs.expected_head_sha }}

    - name: Teardown complete
      shell: bash
      run: |
        set -euo pipefail
        echo "PS.TEARDOWN: OK"
