# ==============================================================================
# Political Sphere — Composite Action: PS Teardown
# License: Proprietary
# ==============================================================================
# ps_header_v: 6
#
# ─────────────────────────────────────────────────────────────────────────────
# IDENTITY
# ─────────────────────────────────────────────────────────────────────────────
# meta:
#   file_id: .github/actions/ps-teardown/ps-exit/action.yml
#   file_type: action
#   language: yaml
#   version: 1.0.0
#   status: active
#   classification: internal
#   owner: political-sphere
#   last_editor: codex
#
# ─────────────────────────────────────────────────────────────────────────────
# LIFECYCLE & CHANGE CONTROL
# ─────────────────────────────────────────────────────────────────────────────
#   lifecycle:
#     created: 2025-12-28
#     last_updated: 2025-12-28
#     last_updated_mode: manual
#     review_cycle: 6 months
#     change_control: lightweight
#
# ─────────────────────────────────────────────────────────────────────────────
# CONTEXT
# ─────────────────────────────────────────────────────────────────────────────
# context:
#   parent_system: CI/CD Platform
#   initiative: Hardened CI
#
# ─────────────────────────────────────────────────────────────────────────────
# GOVERNANCE
# ─────────────────────────────────────────────────────────────────────────────
# governance:
#   intent: Provide the PS Teardown composite action to Canonical job teardown
#     switchboard: summary, artifacts, optional PR comment.
#   guarantees:
#     - Defines inputs and outputs for consistent downstream usage.
#     - Executes the composite steps declared in this action.
#     - Uses pinned external actions when referenced.
#   prohibitions:
#     - Does not grant permissions beyond the invoking workflow.
#     - Does not assume network access beyond runner policy.
#
# ─────────────────────────────────────────────────────────────────────────────
# INTERFACES
# ─────────────────────────────────────────────────────────────────────────────
# interfaces:
#   inputs: [summary_workflow, summary_output_path, summary_results, artifacts_name,
#     artifacts_paths, artifacts_retention_days, artifacts_if_no_files_found,
#     artifacts_compression_level, pr_number, github_token, pr_comment_body,
#     pr_comment_body_path, pr_comment_body_prefix, pr_comment_body_suffix,
#     expected_base_sha, expected_head_sha]
#   outputs: [none]
#   exit_codes: [0=success, 1=failure]
#
# ─────────────────────────────────────────────────────────────────────────────
# EXECUTION
# ─────────────────────────────────────────────────────────────────────────────
# execution:
#   invocation: Used as a composite action step in GitHub Actions workflows.
#   example_invocation: >-
#     uses: ./.github/actions/ps-teardown/ps-exit
#   model: deterministic
#   idempotency: not guaranteed
#
# ─────────────────────────────────────────────────────────────────────────────
# DEPENDENCIES
# ─────────────────────────────────────────────────────────────────────────────
# dependencies:
#   internal: [tools/scripts/core/gha-helpers.sh,
#     tools/scripts/core/string.sh]
#   external: [bash]
#
# ─────────────────────────────────────────────────────────────────────────────
# SECURITY & POLICY
# ─────────────────────────────────────────────────────────────────────────────
# security:
#   permissions: [none]
#   secrets: [github_token]
#   network: restricted; depends on runner policy
#   policy_enforcement: [configs/ci/policies/allowed-actions.yml,
#     configs/ci/policies/action-pinning.yml,
#     configs/ci/policies/inline-bash.yml,
#     configs/ci/policies/section-headers.yml]
#
# ─────────────────────────────────────────────────────────────────────────────
# OPERATIONS
# ─────────────────────────────────────────────────────────────────────────────
# ops:
#   failure_modes: Step failures or validation errors surface as non-zero exits.
#   observability: Step logs are emitted in the GitHub Actions job output.
#   performance: Seconds to minutes depending on repo size and workload.
#
# ─────────────────────────────────────────────────────────────────────────────
# RISKS
# ─────────────────────────────────────────────────────────────────────────────
# risks:
#   assumptions:
#     - Inputs are provided as documented.
#     - Runner has required tooling for declared steps.
#   known_risks:
#     - Network or platform outages can interrupt execution.
#
# ─────────────────────────────────────────────────────────────────────────────
# RELATED
# ─────────────────────────────────────────────────────────────────────────────
# related:
#   references:
#     - tools/scripts/core/gha-helpers.sh
#     - tools/scripts/core/string.sh
#
# ==============================================================================

name: "PS Teardown"
description: "Canonical job teardown switchboard: summary, artifacts, optional PR comment"

inputs:
  summary_workflow:
    description: "Workflow identifier for the summary payload (optional)"
    required: false
    default: ""

  summary_output_path:
    description: "Output path for the summary JSON (repo-relative, optional)"
    required: false
    default: ""

  summary_results:
    description: "Newline-separated key=value result pairs (optional)"
    required: false
    default: ""

  artifacts_name:
    description: "Artifact name to upload (optional)"
    required: false
    default: ""

  artifacts_paths:
    description: "Paths to upload (newline-separated globs, optional)"
    required: false
    default: ""

  artifacts_retention_days:
    description: "Artifact retention days (optional)"
    required: false
    default: "7"

  artifacts_if_no_files_found:
    description: "Behavior when no files are found: warn | error | ignore"
    required: false
    default: "warn"

  artifacts_compression_level:
    description: "Zlib compression level (0-9)"
    required: false
    default: "6"

  pr_number:
    description: "Optional PR number to comment on"
    required: false
    default: ""

  github_token:
    description: "Token for posting PR comments (issues: write)"
    required: false
    default: ""

  pr_comment_body:
    description: "Optional PR comment body (markdown)"
    required: false
    default: ""

  pr_comment_body_path:
    description: "Optional path to PR comment body file (repo-relative)"
    required: false
    default: ""

  pr_comment_body_prefix:
    description: "Optional prefix for PR comment body when using pr_comment_body_path"
    required: false
    default: ""

  pr_comment_body_suffix:
    description: "Optional suffix for PR comment body when using pr_comment_body_path"
    required: false
    default: ""

  expected_base_sha:
    description: "Optional expected base SHA for PR comment validation"
    required: false
    default: ""

  expected_head_sha:
    description: "Optional expected head SHA for PR comment validation"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Resolve inputs (PS)
      id: ps_teardown_inputs
      shell: bash
      env:
        PS_SUMMARY_WORKFLOW: ${{ inputs.summary_workflow }}
        PS_SUMMARY_OUTPUT_PATH: ${{ inputs.summary_output_path }}
        PS_SUMMARY_RESULTS: ${{ inputs.summary_results }}
        PS_ARTIFACTS_NAME: ${{ inputs.artifacts_name }}
        PS_ARTIFACTS_PATHS: ${{ inputs.artifacts_paths }}
        PS_PR_NUMBER: ${{ inputs.pr_number }}
        PS_GITHUB_TOKEN: ${{ inputs.github_token }}
        PS_PR_BODY: ${{ inputs.pr_comment_body }}
        PS_PR_BODY_PATH: ${{ inputs.pr_comment_body_path }}
        PS_PR_BODY_PREFIX: ${{ inputs.pr_comment_body_prefix }}
        PS_PR_BODY_SUFFIX: ${{ inputs.pr_comment_body_suffix }}
      run: |
        set -euo pipefail

        # shellcheck source=tools/scripts/core/string.sh
        . "${GITHUB_WORKSPACE}/tools/scripts/core/string.sh"

        # shellcheck source=tools/scripts/core/gha-helpers.sh
        . "${GITHUB_WORKSPACE}/tools/scripts/core/gha-helpers.sh"
        # shellcheck source=tools/scripts/core/validation.sh
        . "${GITHUB_WORKSPACE}/tools/scripts/core/validation.sh"

        fail() {
          v_error "$*"
          exit 1
        }

        summary_workflow="$(trim "${PS_SUMMARY_WORKFLOW}")"
        summary_output_path="$(trim "${PS_SUMMARY_OUTPUT_PATH}")"
        summary_results="$(trim "${PS_SUMMARY_RESULTS}")"
        artifacts_name="$(trim "${PS_ARTIFACTS_NAME}")"
        artifacts_paths="$(trim "${PS_ARTIFACTS_PATHS}")"
        pr_number="$(trim "${PS_PR_NUMBER}")"
        github_token="$(trim "${PS_GITHUB_TOKEN}")"
        pr_body="$(trim "${PS_PR_BODY}")"
        pr_body_path="$(trim "${PS_PR_BODY_PATH}")"
        pr_body_prefix="${PS_PR_BODY_PREFIX:-}"
        pr_body_suffix="${PS_PR_BODY_SUFFIX:-}"

        run_summary="0"
        if [[ -n "${summary_workflow}" || \
          -n "${summary_output_path}" || \
          -n "${summary_results}" ]]; then
          if [[ -z "${summary_workflow}" || \
            -z "${summary_output_path}" || \
            -z "${summary_results}" ]]; then
            fail "summary_workflow, summary_output_path, and summary_results must be"
            fail "provided together."
          fi
          run_summary="1"
        fi

        run_artifacts="0"
        if [[ -n "${artifacts_name}" || -n "${artifacts_paths}" ]]; then
          if [[ -z "${artifacts_name}" || -z "${artifacts_paths}" ]]; then
            fail "artifacts_name and artifacts_paths must be provided together."
          fi
          run_artifacts="1"
        fi

        run_pr_comment="0"
        if [[ -n "${pr_number}" || -n "${github_token}" || -n "${pr_body}" ]]; then
          if [[ -z "${pr_number}" || -z "${github_token}" ]]; then
            fail "pr_number and github_token are required to post a PR comment."
          fi
          run_pr_comment="1"
        fi

        if [[ -z "${pr_body}" && -n "${pr_body_path}" ]]; then
          if [[ "${pr_body_path}" == /* || "${pr_body_path}" == *".."* ]]; then
            fail "pr_comment_body_path must be repo-relative and must not include '..'."
          fi
          body_file="${GITHUB_WORKSPACE}/${pr_body_path}"
          if [[ ! -f "${body_file}" ]]; then
            fail "pr_comment_body_path not found: ${body_file}"
          fi
          pr_body="${pr_body_prefix}$(cat "${body_file}")${pr_body_suffix}"
        fi

        if [[ -z "${pr_body}" ]]; then
          if [[ -n "${summary_workflow}" ]]; then
            pr_body="Automated CI teardown report for workflow \`${summary_workflow}\`."
          else
            pr_body="Automated CI teardown report."
          fi
        fi

        emit_output "run_summary" "${run_summary}"
        emit_output "run_artifacts" "${run_artifacts}"
        emit_output "run_pr_comment" "${run_pr_comment}"
        emit_output "pr_body" "${pr_body}"

    - name: Write summary (PS)
      if: ${{ steps.ps_teardown_inputs.outputs.run_summary == '1' }}
      uses: ./.github/actions/ps-write-summary
      with:
        workflow: ${{ inputs.summary_workflow }}
        output_path: ${{ inputs.summary_output_path }}
        results: ${{ inputs.summary_results }}

    - name: Upload artifacts (PS)
      if: ${{ steps.ps_teardown_inputs.outputs.run_artifacts == '1' }}
      uses: ./.github/actions/ps-upload-artifacts
      with:
        name: ${{ inputs.artifacts_name }}
        path: ${{ inputs.artifacts_paths }}
        retention_days: ${{ inputs.artifacts_retention_days }}
        if_no_files_found: ${{ inputs.artifacts_if_no_files_found }}
        compression_level: ${{ inputs.artifacts_compression_level }}

    - name: Post PR comment (PS)
      if: ${{ steps.ps_teardown_inputs.outputs.run_pr_comment == '1' }}
      uses: ./.github/actions/ps-pr-comment
      with:
        pr_number: ${{ inputs.pr_number }}
        body: ${{ steps.ps_teardown_inputs.outputs.pr_body }}
        github_token: ${{ inputs.github_token }}
        expected_base_sha: ${{ inputs.expected_base_sha }}
        expected_head_sha: ${{ inputs.expected_head_sha }}

    - name: Complete (PS)
      shell: bash
      run: |
        set -euo pipefail
        printf 'PS.TEARDOWN.EXIT: OK\n'
