# ==============================================================================
# Political Sphere — Composite Action: JSCPD
# License: Proprietary
# ==============================================================================
# ps_header_v: 6
#
# ─────────────────────────────────────────────────────────────────────────────
# IDENTITY
# ─────────────────────────────────────────────────────────────────────────────
# meta:
#   file_id: .github/actions/ps-task/jscpd/action.yml
#   file_type: action
#   language: yaml
#   version: 1.0.0
#   status: active
#   classification: internal
#   owner: political-sphere
#   last_editor: codex
#
# ─────────────────────────────────────────────────────────────────────────────
# LIFECYCLE & CHANGE CONTROL
# ─────────────────────────────────────────────────────────────────────────────
#   lifecycle:
#     created: 2025-12-28
#     last_updated: 2025-12-28
#     last_updated_mode: manual
#     review_cycle: 6 months
#     change_control: lightweight
#
# ─────────────────────────────────────────────────────────────────────────────
# CONTEXT
# ─────────────────────────────────────────────────────────────────────────────
# context:
#   parent_system: CI/CD Platform
#   initiative: Hardened CI
#
# ─────────────────────────────────────────────────────────────────────────────
# GOVERNANCE
# ─────────────────────────────────────────────────────────────────────────────
# governance:
#   intent: Provide the JSCPD composite action to Run duplication detection.
#   guarantees:
#     - Defines inputs and outputs for consistent downstream usage.
#     - Executes the composite steps declared in this action.
#     - Uses pinned external actions when referenced.
#   prohibitions:
#     - Does not grant permissions beyond the invoking workflow.
#     - Does not assume network access beyond runner policy.
#
# ─────────────────────────────────────────────────────────────────────────────
# INTERFACES
# ─────────────────────────────────────────────────────────────────────────────
# interfaces:
#   inputs: [threshold]
#   outputs: [none]
#   exit_codes: [0=success, 1=failure]
#
# ─────────────────────────────────────────────────────────────────────────────
# EXECUTION
# ─────────────────────────────────────────────────────────────────────────────
# execution:
#   invocation: Used as a composite action step in GitHub Actions workflows.
#   example_invocation: >-
#     uses: ./.github/actions/ps-task/jscpd
#   model: deterministic
#   idempotency: not guaranteed
#
# ─────────────────────────────────────────────────────────────────────────────
# DEPENDENCIES
# ─────────────────────────────────────────────────────────────────────────────
# dependencies:
#   internal: [tools/scripts/actions/ps-jscpd/jscpd.sh, configs/lint/jscpd.json]
#   external: [none]
#
# ─────────────────────────────────────────────────────────────────────────────
# SECURITY & POLICY
# ─────────────────────────────────────────────────────────────────────────────
# security:
#   permissions: [none]
#   secrets: [none]
#   network: restricted; depends on runner policy
#   policy_enforcement: [configs/ci/policies/allowed-actions.yml,
#     configs/ci/policies/action-pinning.yml,
#     configs/ci/policies/inline-bash.yml,
#     configs/ci/policies/section-headers.yml]
#
# ─────────────────────────────────────────────────────────────────────────────
# OPERATIONS
# ─────────────────────────────────────────────────────────────────────────────
# ops:
#   failure_modes: Step failures or validation errors surface as non-zero exits.
#   observability: Step logs are emitted in the GitHub Actions job output.
#   performance: Seconds to minutes depending on repo size and workload.
#
# ─────────────────────────────────────────────────────────────────────────────
# RISKS
# ─────────────────────────────────────────────────────────────────────────────
# risks:
#   assumptions:
#     - Inputs are provided as documented.
#     - Runner has required tooling for declared steps.
#   known_risks:
#     - Network or platform outages can interrupt execution.
#
# ─────────────────────────────────────────────────────────────────────────────
# RELATED
# ─────────────────────────────────────────────────────────────────────────────
# related:
#   references:
#     - .github/actions/ps-task/jscpd/README.md
#     - tools/scripts/actions/ps-jscpd/jscpd.sh
#     - configs/lint/jscpd.json
#
# ==============================================================================

name: "JSCPD"
description: "Run duplication detection"

inputs:
  threshold:
    description: "Duplication threshold percentage"
    required: false
    default: "5"

runs:
  using: "composite"
  steps:
    - name: Run JSCPD (PS)
      uses: ./.github/actions/ps-task/ps-run
      with:
        id: "jscpd"
        title: "Duplication detection"
        description: "Code duplication scanning"
        script: "tools/scripts/actions/ps-jscpd/jscpd.sh"
        require_files: |
          configs/lint/jscpd.json
          tools/scripts/actions/ps-jscpd/jscpd.sh
        env_kv: |
          JSCPD_THRESHOLD=${{ inputs.threshold }}

    - name: Complete (PS)
      shell: bash
      run: |
        set -euo pipefail
        printf 'PS.TASK.JSCPD: OK\n'
