# ==============================================================================
# Political Sphere — Composite Action: JSCPD
# ------------------------------------------------------------------------------
# Purpose:
#   Detect code duplication with platform defaults.
#
# Metadata:
#   - Created: 2025-12-20
#   - Last updated: 2025-12-20
#
# Scope & Responsibilities:
#   - Does: execute JSCPD against the repository with standard config.
#   - Does NOT: run other linting or testing gates.
#
# Design Principles:
#   - Deterministic and non-interactive execution
#   - CI-safe with structured output
#   - Delegates to a single script for consistency
#
# Dependencies:
#   - ./.github/actions/ps-task/ps-run
#   - tools/scripts/actions/ps-jscpd/jscpd.sh
#   - configs/lint/jscpd.json
#
# Dependents:
#   - ./.github/workflows/pr-gates.yml
#
# Execution Model:
#   - Trigger: N/A (invoked by workflow steps)
#   - Type: composite action (internal-only)
#   - Invoked by: PR gates workflow
#
# Security & Policy Notes:
#   - Secrets: none
#   - Permissions: inherited from the caller (read-only expected)
#   - Constraints: requires jscpd installed (npm dependency)
#
# Operational Notes:
#   - Timeouts: controlled by the calling job
#   - Artifacts: produced by the JSCPD script (reports/**, logs/**)
#   - CI vs local: same script used by local gates
# ==============================================================================

name: "JSCPD"
description: "Run duplication detection"

inputs:
  threshold:
    description: "Duplication threshold percentage"
    required: false
    default: "5"

runs:
  using: "composite"
  steps:
    - name: Run JSCPD (PS)
      uses: ./.github/actions/ps-task/ps-run
      with:
        id: "jscpd"
        title: "Duplication detection"
        description: "Code duplication scanning"
        script: "tools/scripts/actions/ps-jscpd/jscpd.sh"
        require_files: |
          configs/lint/jscpd.json
          tools/scripts/actions/ps-jscpd/jscpd.sh
        env_kv: |
          JSCPD_THRESHOLD=${{ inputs.threshold }}
