# ==============================================================================
# Political Sphere — Composite Action: Lint Toolchain
# ------------------------------------------------------------------------------
# Purpose:
#   Install pinned linting CLI tools used by CI lint gates.
#
# Metadata:
#   - Created: 2025-12-20
#   - Last updated: 2025-12-20
#
# Scope & Responsibilities:
#   - Does: install actionlint, shellcheck, hadolint, yamllint.
#   - Does NOT: run lint checks or modify workflow permissions.
#
# Design Principles:
#   - Deterministic, pinned versions + SHA256 verification
#   - Non-interactive execution
#   - Minimal surface area with explicit inputs
#
# Dependencies:
#   - ./.github/actions/ps-install-tools
#
# Dependents:
#   - ./.github/workflows/pr-gates.yml
#
# Execution Model:
#   - Trigger: N/A (invoked by workflow steps)
#   - Type: composite action (internal-only)
#
# Security & Policy Notes:
#   - Secrets: none
#   - Permissions: inherited from the caller
#   - Constraints: Linux-only (GitHub-hosted ubuntu runners)
#
# Operational Notes:
#   - Timeouts: controlled by the calling job
#   - Artifacts: none
#   - CI vs local: designed for CI usage only
# ==============================================================================

name: "PS Lint Tools"
description: "Install pinned linting CLIs for CI gates"

inputs:
  install_dir:
    description: "Installation directory for CLI tools (repo-relative)"
    required: false
    default: ".tooling/bin"

runs:
  using: "composite"
  steps:
    - name: Install lint tools (PS)
      uses: ./.github/actions/ps-install-tools
      with:
        install_dir: ${{ inputs.install_dir }}
        tools: "actionlint,shellcheck,hadolint,yamllint"
