name: "PS Lint Tools"
description: "Wrapper to install lint tools via ps-tools (bundle: lint)"

inputs:
  skip_install:
    description: "Skip actual install (1|0). Pass-through for compatibility"
    required: false
    default: "0"

runs:
  using: "composite"
  steps:
    - name: Install lint tools
      uses: ./.github/actions/ps-tools
      with:
        bundle: "lint"
