# ==============================================================================
# Political Sphere — Composite Action: PS Banner
# ------------------------------------------------------------------------------
# Purpose:
#   Print the Political Sphere ASCII banner for consistent branding.
#
# Requirements:
#   - PS_PLATFORM_ROOT must point to the checked-out platform repo
#     (e.g. ${{ github.workspace }}/.ps-platform)
# ==============================================================================

name: "PS Banner"
description: "Prints the Political Sphere ASCII banner"

runs:
  using: "composite"
  steps:
    - name: Print Political Sphere banner
      shell: bash
      run: |
        set -euo pipefail

        : "${PS_PLATFORM_ROOT:?PS_PLATFORM_ROOT must be set by the workflow (path to checked-out platform repo)}"

        platform_root="${PS_PLATFORM_ROOT}"
        script="${platform_root}/tools/scripts/branding/print-banner.sh"
        banner="${platform_root}/branding/ps-banner.txt"

        echo "PS.BANNER: platform_root=${platform_root}"
        echo "PS.BANNER: script=${script}"
        echo "PS.BANNER: banner=${banner}"

        if [[ ! -d "${platform_root}" ]]; then
          echo "ERROR: PS_PLATFORM_ROOT directory not found: ${platform_root}" >&2
          exit 1
        fi

        if [[ ! -f "${script}" ]]; then
          echo "ERROR: print-banner.sh not found at ${script}" >&2
          exit 1
        fi

        if [[ ! -f "${banner}" ]]; then
          echo "ERROR: ps-banner.txt not found at ${banner}" >&2
          exit 1
        fi

        # If your script expects the banner path as an argument, keep this:
        bash "${script}" "${banner}"

        # If your script instead reads a fixed path internally, use this:
        # bash "${script}"

        echo "PS.BANNER: OK"
