# ==============================================================================
# Political Sphere — Composite Action: CI Validate
# License: Proprietary
# ==============================================================================
# ps_header_v: 6
#
# ─────────────────────────────────────────────────────────────────────────────
# IDENTITY
# ─────────────────────────────────────────────────────────────────────────────
# meta:
#   file_id: .github/actions/ps-ci-validate/action.yml
#   file_type: action
#   language: yaml
#   version: 1.0.0
#   status: active
#   classification: internal
#   owner: political-sphere
#   last_editor: codex
#
# ─────────────────────────────────────────────────────────────────────────────
# LIFECYCLE & CHANGE CONTROL
# ─────────────────────────────────────────────────────────────────────────────
#   lifecycle:
#     created: 2025-12-28
#     last_updated: 2025-12-28
#     last_updated_mode: manual
#     review_cycle: 6 months
#     change_control: lightweight
#
# ─────────────────────────────────────────────────────────────────────────────
# CONTEXT
# ─────────────────────────────────────────────────────────────────────────────
# context:
#   parent_system: CI/CD Platform
#   initiative: Hardened CI
#
# ─────────────────────────────────────────────────────────────────────────────
# GOVERNANCE
# ─────────────────────────────────────────────────────────────────────────────
# governance:
#   intent: Provide the CI Validate composite action to Runs the Validate-CI policy
#     gate (Political Sphere).
#   guarantees:
#     - Defines inputs and outputs for consistent downstream usage.
#     - Executes the composite steps declared in this action.
#     - Uses pinned external actions when referenced.
#   prohibitions:
#     - Does not grant permissions beyond the invoking workflow.
#     - Does not assume network access beyond runner policy.
#
# ─────────────────────────────────────────────────────────────────────────────
# INTERFACES
# ─────────────────────────────────────────────────────────────────────────────
# interfaces:
#   inputs: [platform_root, script_relpath]
#   outputs: [platform_root]
#   exit_codes: [0=success, 1=failure]
#
# ─────────────────────────────────────────────────────────────────────────────
# EXECUTION
# ─────────────────────────────────────────────────────────────────────────────
# execution:
#   invocation: Used as a composite action step in GitHub Actions workflows.
#   example_invocation: >-
#     uses: ./.github/actions/ps-ci-validate
#   model: deterministic
#   idempotency: not guaranteed
#
# ─────────────────────────────────────────────────────────────────────────────
# DEPENDENCIES
# ─────────────────────────────────────────────────────────────────────────────
# dependencies:
#   internal: [tools/scripts/ci/validate-ci-action.sh, tools/scripts/branding/format.sh,
#     tools/scripts/branding/safe-format.sh,
#     tools/scripts/actions/cross-cutting/output.sh]
#   external: [bash]
#
# ─────────────────────────────────────────────────────────────────────────────
# SECURITY & POLICY
# ─────────────────────────────────────────────────────────────────────────────
# security:
#   permissions: [none]
#   secrets: [none]
#   network: restricted; depends on runner policy
#   policy_enforcement: [configs/ci/policies/allowed-actions.yml,
#     configs/ci/policies/action-pinning.yml,
#     configs/ci/policies/inline-bash.yml,
#     configs/ci/policies/section-headers.yml]
#
# ─────────────────────────────────────────────────────────────────────────────
# OPERATIONS
# ─────────────────────────────────────────────────────────────────────────────
# ops:
#   failure_modes: Step failures or validation errors surface as non-zero exits.
#   observability: Step logs are emitted in the GitHub Actions job output.
#   performance: Seconds to minutes depending on repo size and workload.
#
# ─────────────────────────────────────────────────────────────────────────────
# RISKS
# ─────────────────────────────────────────────────────────────────────────────
# risks:
#   assumptions:
#     - Inputs are provided as documented.
#     - Runner has required tooling for declared steps.
#   known_risks:
#     - Network or platform outages can interrupt execution.
#
# ─────────────────────────────────────────────────────────────────────────────
# RELATED
# ─────────────────────────────────────────────────────────────────────────────
# related:
#   references:
#     - .github/actions/ps-ci-validate/README.md
#     - tools/scripts/ci/validate-ci-action.sh
#     - tools/scripts/branding/format.sh
#     - tools/scripts/branding/safe-format.sh
#     - tools/scripts/actions/cross-cutting/output.sh
#
# ==============================================================================

name: "CI Validate"
description: "Runs the Validate-CI policy gate (Political Sphere)"

inputs:
  platform_root:
    description: "Absolute path to platform checkout directory. Defaults to env.PS_PLATFORM_ROOT."
    required: false
    default: ""

  script_relpath:
    description: "Script path relative to the repository root."
    required: false
    default: "tools/scripts/ci/validate-ci-action.sh"

outputs:
  platform_root:
    description: "Resolved platform root used for validation"
    value: ${{ steps.resolve.outputs.platform_root }}

runs:
  using: "composite"
  steps:
    - name: Resolve & validate inputs (PS)
      id: resolve
      shell: bash
      env:
        PS_PLATFORM_ROOT_INPUT: ${{ inputs.platform_root }}
        PS_PLATFORM_ROOT_ENV: ${{ env.PS_PLATFORM_ROOT }}
        PS_SCRIPT_RELPATH: ${{ inputs.script_relpath }}
      run: |
        set -euo pipefail

        # Resolve platform root: prefer explicit input, else env.
        platform_root="${PS_PLATFORM_ROOT_INPUT:-}"
        if [[ -z "${platform_root}" ]]; then
          platform_root="${PS_PLATFORM_ROOT_ENV:-}"
        fi

        if [[ -z "${platform_root}" ]]; then
          printf 'ERROR: CI Validate requires platform root.\n' >&2
          printf 'Set inputs.platform_root or env.PS_PLATFORM_ROOT (e.g. %s/.ps-platform).\n' \
            "${GITHUB_WORKSPACE}" >&2
          exit 1
        fi

        # Require an absolute path (prevents ambiguity + path traversal).
        if [[ "${platform_root}" != /* ]]; then
          printf 'ERROR: platform_root must be an absolute path (got %q)\n' "${platform_root}" >&2
          exit 1
        fi

        if [[ ! -d "${platform_root}" ]]; then
          printf 'ERROR: platform_root directory not found: %q\n' "${platform_root}" >&2
          exit 1
        fi

        script_rel="${PS_SCRIPT_RELPATH:-tools/scripts/ci/validate-ci-action.sh}"
        if [[ -z "${script_rel}" ]]; then
          printf 'ERROR: inputs.script_relpath must not be empty\n' >&2
          exit 1
        fi

        # Script is expected to live in the *repo*, not the platform repo.
        # That keeps Validate-CI runnable regardless of platform structure.
        script_abs="${GITHUB_WORKSPACE}/${script_rel}"
        if [[ ! -f "${script_abs}" ]]; then
          printf 'ERROR: Validate-CI script not found at %q\n' "${script_abs}" >&2
          printf 'Expected relative path: %q\n' "${script_rel}" >&2
          exit 1
        fi

        printf 'PS.CI_VALIDATE: platform_root=%s\n' "${platform_root}"
        printf 'PS.CI_VALIDATE: script=%s\n' "${script_abs}"

        # shellcheck source=tools/scripts/actions/cross-cutting/output.sh
        . "${GITHUB_WORKSPACE}/tools/scripts/actions/cross-cutting/output.sh"

        emit_output "platform_root" "${platform_root}"
        emit_output "script_abs" "${script_abs}"

    - name: Run Validate-CI gate (PS)
      shell: bash
      env:
        PS_PLATFORM_ROOT: ${{ steps.resolve.outputs.platform_root }}
        PS_VALIDATE_SCRIPT_ABS: ${{ steps.resolve.outputs.script_abs }}
      run: |
        set -euo pipefail
        script="${PS_VALIDATE_SCRIPT_ABS}"

        # shellcheck source=tools/scripts/branding/safe-format.sh
        . "${GITHUB_WORKSPACE}/tools/scripts/branding/safe-format.sh"
        if ps_format_try_load "${GITHUB_WORKSPACE}" "" "PS.CI.VALIDATE"; then
          if type -t ps_header >/dev/null 2>&1; then
            ps_header "Policy Gate: CI Validation"
          fi
        fi

        # Ensure executable bit isn't required (CI runners can run via bash).
        bash "${script}"

    - name: CI Validate complete (PS)
      shell: bash
      run: |
        set -euo pipefail
        printf 'PS.CI_VALIDATE: OK\n'
