# ==============================================================================
# Political Sphere — Composite Action: TruffleHog (PR)
# License: Proprietary
# ==============================================================================
# ps_header_v: 6
#
# ─────────────────────────────────────────────────────────────────────────────
# IDENTITY
# ─────────────────────────────────────────────────────────────────────────────
# meta:
#   file_id: .github/actions/ps-task/secret-detection/action.yml
#   file_type: action
#   language: yaml
#   version: 1.0.0
#   status: active
#   classification: internal
#   owner: political-sphere
#   last_editor: codex
#
# ─────────────────────────────────────────────────────────────────────────────
# LIFECYCLE & CHANGE CONTROL
# ─────────────────────────────────────────────────────────────────────────────
#   lifecycle:
#     created: 2025-12-28
#     last_updated: 2025-12-28
#     last_updated_mode: manual
#     review_cycle: 6 months
#     change_control: lightweight
#
# ─────────────────────────────────────────────────────────────────────────────
# CONTEXT
# ─────────────────────────────────────────────────────────────────────────────
# context:
#   parent_system: CI/CD Platform
#   initiative: Hardened CI
#
# ─────────────────────────────────────────────────────────────────────────────
# GOVERNANCE
# ─────────────────────────────────────────────────────────────────────────────
# governance:
#   intent: Provide the TruffleHog (PR) composite action to Run TruffleHog scan and
#     move SARIF to reports/security/trufflehog.sarif.
#   guarantees:
#     - Defines inputs and outputs for consistent downstream usage.
#     - Executes the composite steps declared in this action.
#     - Uses pinned external actions when referenced.
#   prohibitions:
#     - Does not grant permissions beyond the invoking workflow.
#     - Does not assume network access beyond runner policy.
#
# ─────────────────────────────────────────────────────────────────────────────
# INTERFACES
# ─────────────────────────────────────────────────────────────────────────────
# interfaces:
#   inputs: [none]
#   outputs: [none]
#   exit_codes: [0=success, 1=failure]
#
# ─────────────────────────────────────────────────────────────────────────────
# EXECUTION
# ─────────────────────────────────────────────────────────────────────────────
# execution:
#   invocation: Used as a composite action step in GitHub Actions workflows.
#   example_invocation: >-
#     uses: ./.github/actions/ps-task/secret-detection
#   model: deterministic
#   idempotency: not guaranteed
#
# ─────────────────────────────────────────────────────────────────────────────
# DEPENDENCIES
# ─────────────────────────────────────────────────────────────────────────────
# dependencies:
#   internal: [none]
#   external: [bash, trufflesecurity/trufflehog@a633174c3b2242aa1b6f8941d2ad6a99e0305964]
#
# ─────────────────────────────────────────────────────────────────────────────
# SECURITY & POLICY
# ─────────────────────────────────────────────────────────────────────────────
# security:
#   permissions: [none]
#   secrets: [none]
#   network: restricted; depends on runner policy
#   policy_enforcement: [configs/ci/policies/allowed-actions.yml,
#     configs/ci/policies/action-pinning.yml,
#     configs/ci/policies/inline-bash.yml,
#     configs/ci/policies/section-headers.yml]
#
# ─────────────────────────────────────────────────────────────────────────────
# OPERATIONS
# ─────────────────────────────────────────────────────────────────────────────
# ops:
#   failure_modes: Step failures or validation errors surface as non-zero exits.
#   observability: Step logs are emitted in the GitHub Actions job output.
#   performance: Seconds to minutes depending on repo size and workload.
#
# ─────────────────────────────────────────────────────────────────────────────
# RISKS
# ─────────────────────────────────────────────────────────────────────────────
# risks:
#   assumptions:
#     - Inputs are provided as documented.
#     - Runner has required tooling for declared steps.
#   known_risks:
#     - Network or platform outages can interrupt execution.
#
# ─────────────────────────────────────────────────────────────────────────────
# RELATED
# ─────────────────────────────────────────────────────────────────────────────
# related:
#   references:
#     - none
#
# ==============================================================================

name: "TruffleHog (PR)"
description: "Run TruffleHog scan and move SARIF to reports/security/trufflehog.sarif"

runs:
  using: "composite"
  steps:
    - name: Run TruffleHog (PS)
      uses: trufflesecurity/trufflehog@a633174c3b2242aa1b6f8941d2ad6a99e0305964
      with:
        format: sarif
        output: trufflehog.sarif

    - name: Move SARIF to reports (PS)
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p reports/security
        if [[ -f trufflehog.sarif ]]; then mv trufflehog.sarif reports/security/trufflehog.sarif; fi

    - name: Complete (PS)
      shell: bash
      run: |
        set -euo pipefail
        printf 'PS.TASK.TRUFFLEHOG: OK\n'
