# ==============================================================================
# Political Sphere — Composite Action: Write Summary
# ------------------------------------------------------------------------------
# Purpose:
#   Write a structured JSON summary artifact for workflow results.
#
# Metadata:
#   - Created: 2025-12-20
#   - Last updated: 2025-12-20
#
# Scope & Responsibilities:
#   - Does: compute overall status and write a JSON summary file.
#   - Does NOT: upload artifacts or alter workflow permissions.
#
# Design Principles:
#   - Deterministic and non-interactive execution
#   - Explicit inputs with validation
#   - CI-safe, machine-readable output
#
# Dependencies:
#   - none (bash only)
#
# Dependents:
#   - ./.github/workflows/pr-gates.yml
#   - ./.github/workflows/security-scheduled.yml
#   - ./.github/workflows/build-artifacts.yml
#   - ./.github/workflows/release.yml
#
# Execution Model:
#   - Trigger: N/A (invoked by workflow steps)
#   - Type: composite action (internal-only)
#
# Security & Policy Notes:
#   - Secrets: none
#   - Permissions: inherited from the caller
#   - Constraints: results must be simple key=value pairs
#
# Operational Notes:
#   - Timeouts: controlled by the calling job
#   - Artifacts: writes a JSON file at inputs.output_path
#   - CI vs local: identical behavior
# ==============================================================================

name: "PS Write Summary"
description: "Write structured summary JSON for workflow results"

inputs:
  workflow:
    description: "Workflow identifier for the summary payload"
    required: true
  output_path:
    description: "Output path for the summary JSON (repo-relative)"
    required: true
  results:
    description: "Newline-separated key=value result pairs"
    required: true

runs:
  using: "composite"
  steps:
    - name: Write summary
      shell: bash
      env:
        PS_SUMMARY_WORKFLOW: ${{ inputs.workflow }}
        PS_SUMMARY_OUTPUT_PATH: ${{ inputs.output_path }}
        PS_SUMMARY_RESULTS: ${{ inputs.results }}
      run: |
        set -euo pipefail

        workflow="${PS_SUMMARY_WORKFLOW:-}"
        output_path="${PS_SUMMARY_OUTPUT_PATH:-}"
        results_block="${PS_SUMMARY_RESULTS:-}"

        if [[ -z "${workflow}" || -z "${output_path}" || -z "${results_block}" ]]; then
          echo "ERROR: workflow, output_path, and results are required." >&2
          exit 1
        fi

        overall="success"
        keys=()
        vals=()

        while IFS= read -r line; do
          [[ -z "${line}" ]] && continue
          key="${line%%=*}"
          val="${line#*=}"

          if [[ "${key}" == "${line}" ]]; then
            printf "ERROR: invalid results entry '%s' (expected key=value).\n" "${line}" >&2
            exit 1
          fi

          if [[ ! "${key}" =~ ^[A-Za-z0-9_-]+$ ]]; then
            printf "ERROR: invalid result key '%s'.\n" "${key}" >&2
            exit 1
          fi

          case "${val}" in
            success|failure|cancelled|skipped) ;;
            *)
              printf "ERROR: invalid result value '%s' for '%s'.\n" "${val}" "${key}" >&2
              exit 1
              ;;
          esac

          keys+=("${key}")
          vals+=("${val}")

          if [[ "${val}" == "failure" ]]; then
            overall="failure"
          elif [[ "${val}" == "cancelled" && "${overall}" != "failure" ]]; then
            overall="cancelled"
          fi
        done <<< "${results_block}"

        output_dir="$(dirname "${output_path}")"
        mkdir -p "${output_dir}"

        json="{\"workflow\":\"${workflow}\",\"status\":\"${overall}\",\"results\":{"
        for i in "${!keys[@]}"; do
          key="${keys[$i]}"
          val="${vals[$i]}"
          if [[ "${i}" -gt 0 ]]; then
            json+=","
          fi
          json+="\"${key}\":\"${val}\""
        done
        json+="}}"

        printf '%s\n' "${json}" > "${output_path}"
        printf 'PS.SUMMARY: workflow=%s\n' "${workflow}"
        printf 'PS.SUMMARY: output=%s\n' "${output_path}"
        printf 'PS.SUMMARY: status=%s\n' "${overall}"
