name: "PS Security Tools"
description: "Wrapper to install security tools via ps-tools (bundle: security)"

inputs:
  skip_install:
    description: "Skip actual install (1|0). Pass-through for compatibility"
    required: false
    default: "0"

runs:
  using: "composite"
  steps:
    - name: Install security tools
      uses: ./.github/actions/ps-tools
      with:
        bundle: "security"
